### ISSUE TITLE
Sketch parray inconsistent start angle and rotation convention

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/cadquery#1001]
```
s = cq.Sketch().parray(20, 20, -50, 8).circle(0.5)
```

Result (master):

![image](https://user-images.githubusercontent.com/16394272/154392188-2227e4b9-d57d-4676-a38f-901e63712e4f.png)

Compare `parray` with `arc` start angle and rotation and `face` rotation. 

```
r = 20
a1 = 20

s = (
    cq.Sketch()
    .parray(r, a1, -50, 8)
    .circle(0.5)
    .reset()
    .arc((0, 0), r, a1, -70)
    .rect(r * 2, 1, a1)
)
```

Result (master):

![image](https://user-images.githubusercontent.com/16394272/154392306-525b5ed0-d7f4-4892-96a7-62e8b8270f37.png)

I had expected the following result.:

![image](https://user-images.githubusercontent.com/16394272/154392377-9a8eb372-11ae-4704-96b2-4500e5a2da14.png)

I think this might be a minor issue left from the initial Sketch implementation.  Perhaps `parray` can be changed similar to #939 where `rect` was found to be 90 degrees off from expected?

**Comment by adam-urbanczyk** [comment]
Absolutely, this needs to be fixed to be consistent with `arc`.
