### ISSUE TITLE
Step -> Stl convert script does not output file

### ISSUE THREAD

**Issue by kfina91** [CadQuery/cadquery#1002]
I have a really simple script:

```
// read command line arguments to args...
model = cq.importers.importStep(args.input)
cq.exporters.export(model, args.output)
```

This works for most models, but for some models the code runs, but does not generate the file and does not throw any exceptions. It just silently fails to write the file.
Unfortuantely I can not share the .step file in question due to licensing.

If I import and export the .step in question in FreeCAD and then run code on the FreeCAD exported file, it works.
From the runtime difference, I assume that the code is already failing in importing the .step.

Can I obtain any info on why it is failing, or can I detect failing files beforehand with some logic?

P.S. In my opinion it would improve cadquery, if some kind of exception would be thrown when the import/export fails.

EDIT: Maybe this is an underlying issue. I know this is the wrong repo for this, but FreeCAD python library fails silently as well. (Do both use the same underlying kernel?)

```
import sys
FREECADPATH = 'C:\\Tools\\FreeCAD192\\bin'
sys.path.append(FREECADPATH)
import FreeCAD
import Part

part = Part.read("./test.step")
part.exportStl("./test.stl")
```

**Comment by jmwright** [comment]
Please note, that without a STEP file that reproduces the problem, there's no way to know if the above will solve your issue.

**Comment by kfina91** [comment]
Thank you for your help!

I'll close this, since this is a OCCT issue rather than a cadquery problem.
