### ISSUE TITLE
Workplane polarArray incorrect startAngle and angle (according to its docstring and convention)

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/cadquery#1006]
From the `polarArray` docstring:
```
        :param startAngle: Starting angle (degrees) of array. 0 degrees is
            situated along local X-axis.
        :param angle: The angle (degrees) to fill with elements. A positive
            value will fill in the counter-clockwise direction.
```

Would you be opposed to correcting `polarArray` behavior to follow the docstring?

There are no doc examples and few other references of usage.  I think the issue wasn't noticed because usage was typically with `angle=360` e.g. #118.

**Comment by adam-urbanczyk** [comment]
Yes, +1
