### ISSUE TITLE
Error when importing cadquery: nptyping.error.InvalidArgumentsError

### ISSUE THREAD

**Issue by roipoussiere** [CadQuery/cadquery#1046]
When trying to import cadquery I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../cadquery/cadquery/__init__.py", line 14, in <module>
    from .occ_impl import exporters
  File ".../cadquery/cadquery/occ_impl/exporters/__init__.py", line 10, in <module>
    from ...cq import Workplane
  File ".../cadquery/cadquery/cq.py", line 61, in <module>
    from .sketch import Sketch
  File ".../cadquery/cadquery/sketch.py", line 28, in <module>
    from .occ_impl.sketch_solver import (
  File ".../cadquery/cadquery/occ_impl/sketch_solver.py", line 236, in <module>
    class SketchConstraintSolver(object):
  File ".../cadquery/cadquery/occ_impl/sketch_solver.py", line 265, in SketchConstraintSolver
    self, x0: Array[(Any,), float]
  File ".../cadquery/.venv/lib/python3.9/site-packages/nptyping/ndarray.py", line 73, in __getitem__
    shape_expression, dtype = _get_from_tuple(item)
  File ".../cadquery/.venv/lib/python3.9/site-packages/nptyping/ndarray.py", line 128, in _get_from_tuple
    raise InvalidArgumentsError(
nptyping.error.InvalidArgumentsError: Unexpected argument '(typing.Any,)', expecting Shape[<ShapeExpression>] or Literal[<ShapeExpression>]
```

I don't use Conda but pip, using the [ocpvtk wheel](https://gist.github.com/fpq473/9392185d722c8be722f61e4d745723ee) I built yesterday, but someone else got the same error using Conda.

This error is really recent, because there was no problem to install and import cadquery yesterday.

So it's strange, because:
- I tried on old commits (for instance 3efb080 published 3 weeks ago) and I get the same error;
- according to a [git blame on the line that imports typish](https://github.com/CadQuery/cadquery/blame/d4b5eec21b4bbec47712084b9f88d43fc8f6c165/cadquery/sketch.py#L19), it was added 5 months ago.

If I use the python cadquery venv I created yesterday I can `import cadquery` and `import typish` (without installing it manually). But if I create a new venv (using the same ocpvtk wheel), I get `ModuleNotFoundError: No module named 'typish'` when trying to import cadquery.

Then if I install typish module and try again, I get the error described above (the suspicious line in the stacktrace is [here](https://github.com/CadQuery/cadquery/blob/master/cadquery/occ_impl/sketch_solver.py#L265)).

**Comment by roipoussiere** [comment]
Ok, the issue appears because of the new release of np-typing (2.0) [published yesterday](https://github.com/ramonhagenaars/nptyping/releases/tag/v2.0.0).

I can fix the error by specifying `nptyping==1.4.4`.

**Comment by sethfischer** [comment]
A work-around until this is fixed in master. When following [Command Line Installation](https://cadquery.readthedocs.io/en/latest/installation.html#command-line-installation), specify nptyping 1.4.4.

```
conda install -c cadquery -c conda-forge cadquery=master nptyping=1.4.4
```

**Comment by lorenzncode** [comment]
Is it preferred to make changes to support nptyping v2.0.0?

**Comment by jmwright** [comment]
@lorenzncode Supporting nptyping 2.x would probably be ideal, but we have to make sure that it doesn't cause problems anywhere else in CQ's dependency tree as well. If it does cause other problems, then we'll have to pin the version to 1.4.4.
