### ISSUE TITLE
placeSketch method is missing from the API Reference

### ISSUE THREAD

**Issue by GandalfDG** [CadQuery/cadquery#1052]
While browsing the documentation I was unable to find any mention of the placeSketch method, other than in an example under the sketch documentation page here: [Sketch/workplane integration](https://cadquery.readthedocs.io/en/latest/sketch.html#workplane-integration) It was difficult to discover as a new user, and once I knew it existed, not being able to find it in the API Reference was an issue.

**Comment by jmwright** [comment]
The [ReadTheDocs search](https://cadquery.readthedocs.io/en/latest/search.html?q=placeSketch&check_keywords=yes&area=default) turns up multiple mentions, including in the [class summary](https://cadquery.readthedocs.io/en/latest/classreference.html?highlight=placeSketch#cadquery.Workplane.placeSketch). Is that not what you were looking for?

**Comment by GandalfDG** [comment]
The search works if you know what you're looking for, but it was difficult to discover that function, which feels like an important one that bridges between the Workplane and Sketch methods of construction. I think it would make sense to have it listed in the Workplane section on this page: [API Reference](https://cadquery.readthedocs.io/en/latest/apireference.html)
