### ISSUE TITLE
Assemble VRML export incorrect rotation

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/cadquery#1069]
From the docs cone example:
```
import cadquery as cq

cone = cq.Solid.makeCone(1, 0, 2)

assy = cq.Assembly()
assy.add(cone, name="cone0", color=cq.Color("blue"))
assy.add(
    cone,
    loc=cq.Location(cq.Vector(0, 0, 0), cq.Vector(1, 0, 0), 180),
    name="cone1",
    color=cq.Color("green"),
)

show_object(assy)

assy.save("out_assy.wrl", "VRML")
cq.exporters.assembly.exportVRML(assy, "out_assy2.wrl")
cq.exporters.export(assy.toCompound(), "out_compound.wrl", "VRML")
```

CQ-Editor view is on the right, with VRML viewer overlay on left:
![image](https://user-images.githubusercontent.com/16394272/165667511-5531d699-6aa5-4b73-b73b-3f9629f7607e.png)

I find that this issue is due to radians/degrees mismatch in `toVTK`.

**Comment by jmwright** [comment]
@lorenzncode So does the conversion need to be one on `rot` [here](https://github.com/CadQuery/cadquery/blob/3581904614b1aa31d0deea4e8cfcf4771e5e1943/cadquery/occ_impl/assembly.py#L185)?

**Comment by lorenzncode** [comment]
Yes, the VTK function expects degrees - confirmed with VTK docs and testing change of `toVTK`.

https://vtk.org/doc/nightly/html/classvtkProp3D.html
