### ISSUE TITLE
Additional Option for STEP Export

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery#1082]
The STEP files generated by our default export process were too large for the KiCAD generator update project, with the files being about 2x larger. Setting the following mode fixed the issue, and seems to be the mode they used in the past (although they used the C++ form).

```python
Interface_Static.SetIVal_s('write.surfacecurve.mode', 0)
```

I added it just above [this line](https://github.com/CadQuery/cadquery/blob/c32c08eb4b6537a6116dd5e5ff2360c7ab038fce/cadquery/occ_impl/exporters/assembly.py#L40) in the source in my local copy.

So my question is this. How should this option be added and exposed in the code? Is this an edge case, or will this option be of use to the broader user base? Please let me know if you have any thoughts @adam-urbanczyk @lorenzncode @dcowden @marcus7070

**Comment by michaelgale** [comment]
This is main reason I added alternative STEP export to [CQ-Kit](https://github.com/michaelgale/cq-kit)--the STEP files with the P-Curves were simply too big.  Furthermore, the floating point residue round off of coordinate values also consumed needless bytes resulting in bigger files.  More details are in the [StepFileExporter](https://github.com/michaelgale/cq-kit/blob/f5820c67030f14ae8e387872ae859ad023983c8e/cqkit/cq_files.py#L198) class docstring.

**Comment by adam-urbanczyk** [comment]
Sounds like a very specific use case. BTW: why would KiCAD use STEP and not the internal format of OCCT (`.brep`) is not clear to me.

**Comment by jmwright** [comment]
@michaelgale @lorenzncode @adam-urbanczyk Please have a look at the PR [here](https://github.com/CadQuery/cadquery/pull/1083) and let me know your thoughts. It only accepts two parameters right now, but the code is set up to allow more without cluttering the method signature later. If you have a suggestion on how to reduce the code duplication let me know.

@adam-urbanczyk I'm not sure of the reasons why the KiCAD team uses STEP, but they've been using it for a long time and so I would expect a fair amount of technical debt that will keep them headed down that path for the foreseeable future.

**Comment by adam-urbanczyk** [comment]
> @michaelgale @lorenzncode @adam-urbanczyk Please have a look at the PR [here](https://github.com/CadQuery/cadquery/pull/1083) and let me know your thoughts. It only accepts two parameters right now, but the code is set up to allow more without cluttering the method signature later. If you have a suggestion on how to reduce the code duplication let me know.
> 
> @adam-urbanczyk I'm not sure of the reasons why the KiCAD team uses STEP, but they've been using it for a long time and so I would expect a fair amount of technical debt that will keep them headed down that path for the foreseeable future.

#1083 looks reasonable

**Comment by michaelgale** [comment]
@jmwright A very welcome extension to the STEP export that I'm sure many folks will appreciate.  Disabling of the P-curve entities will have the biggest impact on file size reduction.  Passing in the extra features as kwargs is clean and will allow for future expansion if desired.

**Comment by jmwright** [comment]
Closing this issue as this specific task was completed in #1083 and #1094 can be used for further discussion about the STEP export options.
