### ISSUE TITLE
Sweep circle in the normal direction

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [CadQuery/cadquery#1092]
```python
import cadquery as cq

pts = [
    (1, 1, 1),
    (1, 2, 2),
    (1, 3, 3),
]
p = cq.Workplane("XY").spline(pts, includeCurrent=True)
s = cq.Workplane("XY").circle(1).sweep(p)
```

Based on #296 , I would like to have the extrusion of the circle in the normal direction only (the idea is to make a classic tube from a set of points).

Unfortunately, this code produces a distorded tube:

![image](https://user-images.githubusercontent.com/40028739/171160191-0906bf3f-a9df-4a62-ae4f-bea2711da68d.png)

Thanks for the help!

**Comment by Jojain** [comment]
You need to have the normal of your circle aligned with the tangent of your spline at the start :
```py
pts = [
    (1, 1, 1),
    (1, 2, 2),
    (1, 3, 3),
]
p = cq.Workplane("XY").spline(pts, includeCurrent=True)
dire = p.val().tangentAt(0)
plane = cq.Plane((0,0,0), normal=dire)
s = cq.Workplane(plane).circle(1).sweep(p)
```

**Comment by RemDelaporteMathurin** [comment]
Thanks for the hint!

**Comment by Jojain** [comment]
Note that this is true for any curve (even straight lines) not only splines

**Comment by jmwright** [comment]
@RemDelaporteMathurin If what you're displaying is the exported STL, you may need to adjust your tolerance settings on the export call. Does it display fine in CQ-editor?

**Comment by RemDelaporteMathurin** [comment]
> @RemDelaporteMathurin If what you're displaying is the exported STL, you may need to adjust your tolerance settings on the export call. Does it display fine in CQ-editor?

Yes this is the STL. I'll play with the tolerances then! Thanks! I didn't use the CQ-editor I'm afraid

**Comment by jmwright** [comment]
You could export a STEP and use an online viewer for a double check too.
