### ISSUE TITLE
ipython install add-on not working 

### ISSUE THREAD

**Issue by puterd** [CadQuery/cadquery#1137]
pip install cadquery[ipython]==2.2.0b0

Returns:
zsh: no matches found: cadquery[ipython]==2.2.0b0

on mac, pip updated

**Comment by jmwright** [comment]
Are you running an M1 Mac?

**Comment by puterd** [comment]
No, on pre M1/M2. I tried reinstalling ipython but still no luck.

**Comment by jmwright** [comment]
What happens if you install cadquery by itself and then install ipython? Do you get the same error?

**Comment by jmwright** [comment]
@puterd I'm going to leave this open until I have time to investigate why the install line given in the readme does not work.

**Comment by fpq473** [comment]
The issue is with how zsh treats `[` and `]`.  This fails with the same message:
```sh
% echo cadquery[ipython]==2.2.0b0    
zsh: no matches found: cadquery[ipython]==2.2.0b0
% 
```
To fix, you can add quotes, e.g.
```sh
% pip install 'cadquery[ipython]==2.2.0b0'
...
```
