### ISSUE TITLE
Font_FontMgr, warning: unable to find font

### ISSUE THREAD

**Issue by alinelena** [CadQuery/cadquery#1146]
trying to use a font like this fails to load it. 

```
Fontconfig error: Cannot load default config file: No such file: (null)
Font_FontMgr, warning: unable to find font './Font_Awesome_6_Brands-Regular-400.otf' [regular]; 'DejaVu Sans' [aspects: regular,bold,italic,bold-italic] [paths: /usr/share/fonts/truetype/DejaVuSans.ttf;/usr/share/fonts/truetype/DejaVuSans-Bold.ttf;/usr/share/fonts/truetype/DejaVuSans-Oblique.ttf;/usr/share/fonts/truetype/DejaVuSans-BoldOblique.ttf] is used instead
```

is not a path or a permissions issue since i copy the font in the current place. also openscad and lualatex have no issue using it. 

[test.tar.gz](https://github.com/CadQuery/cadquery/files/9493674/test.tar.gz)

cadquery version 2.2.0b1 and fontconfig is 2.14.0

**Comment by adam-urbanczyk** [comment]
You want to specify the font path (thus not name), so try using the `fontPath` parameter. 

See the docs: https://cadquery.readthedocs.io/en/latest/classreference.html#cadquery.Workplane.text

**Comment by alinelena** [comment]
first fontPath containing absolute path to the font ( filename included) worked.
this is some confusing but worked.

**Comment by adam-urbanczyk** [comment]
@alinelena works for me, check the preferences in CQ-editor

![afbeelding](https://user-images.githubusercontent.com/13981538/189288512-40a85cfd-adc3-4562-948a-c63040c3c8d1.png)
