### ISSUE TITLE
extend tolerance or precision from sweep function

### ISSUE THREAD

**Issue by phiser678** [CadQuery/cadquery#1152]
The sweep function is acting strange when thin! Anybody can help?

## To Reproduce

```python
```
path= cq.Workplane("XZ").spline([(0,0),(20,100/2),(0,100)])
sweep=cq.Workplane("XY").circle(1).sweep(path)

![2022-09-13_11-15](https://user-images.githubusercontent.com/22682880/189883168-bd877f42-da9b-451e-8453-f270cef56dfc.png)
However if I use `circle(2.2)` it is correct. Seems like precision errors?

## Environment
OS: Ubuntu 22.04 
Using:
Python 3.10.4
cadquery==2.2.0b1
cq_editor/_version.py = "0.3.0dev"

**Comment by lorenzncode** [comment]
This is an OCCT tessellation issue (duplicate of #969).

Tessellation impacts both STL export and CQ-editor visualization.

See the comment in #969 for STL export workaround using netgen.  Then even if you don't need STL you could visualize the model from STL file or export STEP and use another viewer.

**Comment by phiser678** [comment]
Thanks for the info, so if I export it to STEP and convert it with netgen to STL it should give the correct result? Let's give that a try!

**Comment by phiser678** [comment]
This code produces a valid result!
```
import netgen.occ as nocc
import netgen.meshing as meshing

s = nocc.OCCGeometry('thintube.step')
m = s.GenerateMesh(perfstepsend=meshing.MeshingStep.MESHSURFACE,maxh=.1,optsteps2d=0)
m.Export('thintube.stl', 'STL Format')
```
![2022-09-14_09-53](https://user-images.githubusercontent.com/22682880/190094951-696823eb-f542-42e3-9d91-39a53514b8a0.png)
