### ISSUE TITLE
Bug in commit 9c525bcfd7bf7f1b8b9aa4370f69cad73806f37a (OCCT7.6)

### ISSUE THREAD

**Issue by berlincode** [CadQuery/cadquery#1162]
Hi and thanks for this great project.

Yesterday I've updated to OCCT7.6. I think I've discoverd a bug in 9c525bcfd7bf7f1b8b9aa4370f69cad73806f37a.

Please consider adding a '+1' to the range target here:
https://github.com/CadQuery/cadquery/blob/master/cadquery/occ_impl/shapes.py#L1221

So this works for me:
"""
poly.Node(i).Transformed(Trsf) for i in range(1, poly.NbNodes()+1)
"""

Thanks

**Comment by adam-urbanczyk** [comment]
Thanks @berlincode , good catch!
