### ISSUE TITLE
Empty leaf node in assembly STEP export

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/cadquery#1170]
This is a follow up to #993.  

The following results in a STEP with empty leaf node "toplevel" due to the empty top/root object.
```py
import cadquery as cq

box = cq.Workplane().box(1, 2, 3)

assy = cq.Assembly(name="toplevel")
assy.add(box, name="box1")
assy.add(box, name="box2", loc=cq.Location((4, 0, 0)))

assy.save("boxes.step")
```

![image](https://user-images.githubusercontent.com/16394272/193951488-14474b7c-9d48-476f-beb3-eae7d97d24eb.png)

I think this leaf node can be considered extraneous.  Is there a use case for the empty leaf node?  If not, I'd suggest to remove it.

Compare with the `toVTK` based export formats where there is a conditional check on shapes:
https://github.com/CadQuery/cadquery/blob/d5806e3d9047fca70aba9f195cd276dc670fdd21/cadquery/occ_impl/assembly.py#L192

**Comment by adam-urbanczyk** [comment]
AFAIR it represents a `Location` - nodes always have a transformation but not always shapes.
