### ISSUE TITLE
dxf export: support layers

### ISSUE THREAD

**Issue by roipoussiere** [CadQuery/cadquery#1171]
ezdxf [supports dxf layers](https://ezdxf.readthedocs.io/en/stable/concepts/layers.html).

For instance, this code generates a dxf file with 256 layers, one for each available color:

```py
import ezdxf
import random

doc = ezdxf.new()
msp = doc.modelspace()

for color in range(256):
    layer_name = f'layer{ color }'
    doc.layers.add(name=layer_name, color=color)

    start = random.randint(0, 100), random.randint(0, 100)
    end = random.randint(0, 100), random.randint(0, 100)
    msp.add_line(start, end, dxfattribs={'layer': layer_name})

doc.saveas('test.dxf')
```

Result (after importing the dxf with Inkscape):
![image](https://user-images.githubusercontent.com/1665542/194519349-0f8147ad-a49c-44af-9d83-16fc81a8ed79.png)

Multi-layers dxf can be used with cnc or laser cutters in order to specify which tool or options must be used for each (ex: one layer to engrave, another one to cut).

Each layers supports:
- a color: which is a number between 0 and 255, corresponding to an index in the [color palette](https://ezdxf.readthedocs.io/en/stable/concepts/aci.html#aci);
- a [line type](https://ezdxf.readthedocs.io/en/stable/concepts/linetypes.html) (continuous, dashed, etc.);
- a [line weight](https://ezdxf.readthedocs.io/en/stable/concepts/lineweights.html), which is a value between 0 and 211 where 1mm = 100 units.

Those options could be passed in the `opt` export attribute:

```py
cq.exporters.export(shape, 'test.dxf', opt={
    'color': 5,
    'line_type': 'dashed',
    'line_weight': 25
})
```

For multi-layers export, I'm not sure what is the best syntax. I have several approaches in mind:

1. pass lists for each option:

```py
cq.exporters.export([shape1, shape2, shape3], 'test.dxf', opt={
    'color': [5, 6, 7],
    'line_type': ['continuous', 'dot', 'dashed'],
    'line_weight': [18, 25, 40]
})
```

2. Add a new class dedicated to DXF export:

```py
layer1 = DxfLayer(shape1, 5, DxfLayer.LineType.CONTINUOUS, 18)
layer2 = DxfLayer(shape2, 6, DxfLayer.LineType.DOT, 25)
layer3 = DxfLayer(shape3, 7, DxfLayer.LineType.DASHED, 40)
cq.exporters.export([ layer1, layer2, layer3 ], 'test.dxf')
```

3. Add 2 classes dedicated to DXF export, one for the layer and one for the model:

```py
layer1 = DxfLayer('layer1', 5, DxfLayer.LineType.CONTINUOUS, 18)
layer2 = DxfLayer('layer2', 6, DxfLayer.LineType.DOT, 25)
layer3 = DxfLayer('layer3', 7, DxfLayer.LineType.DASHED, 40)

dxf_model = (DxfModel()
    .add(shape1, layer1)
    .add(shape2, layer2)
    .add(shape3, layer3)
)

cq.exporters.export(dxf_model, 'test.dxf')
```

I would like to work on this, since I need this for my project, so any advice on the export syntax will be welcome.

**Comment by adam-urbanczyk** [comment]
Maybe something like (1), but pass a `Dict[cq.Shape, Dict[str,Any]]` that maps shapes to their option dicts?

**Comment by sethfischer** [comment]
@roipoussiere I've been working on a utility class for multilayer DXF documents. See  #1267. I've taken the approach not the change the behaviour of `cadquery.exporters.export` but `cadquery.exporters.export` has been refactored to call the utility class.
