### ISSUE TITLE
Polar array support with changing orientation

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#118]
Currently there is no easy way to achieve the right result:

![afbeelding](https://user-images.githubusercontent.com/13981538/54803179-bd722a00-4c6e-11e9-9785-cc180291e00a.png)

Wheras it is trival to get to the left one:
```python
r1 = cq.Workplane("XY" )\
    .box(10, 10, 1).faces(">Z")\
    .polarArray(3.5,0,360,6).rect(1.6,1.6).cutThruAll()
```

I think the right scenario occurs quite frequently, so it would make sense to support it.

Related to:
https://github.com/CadQuery/CQ-editor/issues/31

**Comment by adam-urbanczyk** [comment]
I was thinking about how to implement it this and came up with the following design

1. extend `geom.Vector` so that it allows to attach a transform object to itself
2. refactor `polarArray` to create `Vectors` with proper rotation transforms attached
3. refactor `eachpoint` to apply the attached transform if it exists

Any thoughts?

**Comment by fapbrandt** [comment]
Hi. Why not in 2.0RC2?

**Comment by jmwright** [comment]
@fapbrandt 2.0RC2 is more about finalizing a stable version of CadQuery that runs closer to the OCC CAD kernel than FreeCAD allowed us to. We accept PRs for new features like this for the 2.0 release candidates, but the core development team probably won't have time to get it done before version 2.1.

**Comment by fapbrandt** [comment]
Thanks for answer, jmwright. I personally will check cq.py to see what I can do in my own code. See you.

**Comment by jmwright** [comment]
@fapbrandt You can probably implement this for use in your own scripts using plugins.

https://cadquery.readthedocs.io/en/latest/extending.html#cadqueryexample-plugins
