### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#12]
Current README is not very informative - ideally it should explain what is the purpose of this fork of cadquery etc.

**Comment by jmwright** [comment]
There was some work done on revamping the CQ 1.0 readme about a year or so ago. I was thinking about copying the README from dcowden/cadquery, adding a "why this fork" section for CQ 2.0, then just cleaning up the rest the way I did with the Sphinx docs. @adam-urbanczyk what are your thoughts?

**Comment by adam-urbanczyk** [comment]
Sounds good, but I'd also propose to trim it somewhat.

**Comment by jmwright** [comment]
@adam-urbanczyk Are there any sections in particular that you would like to see cut?

**Comment by adam-urbanczyk** [comment]
Take a look at #99 (it is a scaffold) . NB: feel free to change it/push new commits.
