### ISSUE TITLE
Assembly and part names does not appear after step file import

### ISSUE THREAD

**Issue by tommy3001** [CadQuery/cadquery#1206]
When I generate an assembly in cadquery and export it as step, the assembly and part names does not appear in Freecad. 
Example Code:

  import cadquery as cq
  from cadquery import exporters
 #jupyter IDE
  from jupyter_cadquery import (
      open_viewer, show, web_color,
      set_defaults, get_defaults, 
      PartGroup, Part, Faces, Edges
  )
  cone = cq.Solid.makeCone(1, 0, 2) 
  assy = cq.Assembly(name="myCone")
  assy.add(
      cone,
      loc=cq.Location(cq.Vector(0, 0, 0), cq.Vector(1, 0, 0), 180),
      name="cone0",
      color=cq.Color("green")
  )
  assy.add(cone, name="cone1", color=cq.Color("blue"))
  
  assy.save('assy.step')

Result after import in Freecad:

![image](https://user-images.githubusercontent.com/538947/208245219-df3b302a-1a51-4e04-ae0c-fa0ed75b54ae.png)

Cadquery version is the actual master branch, Freecad version is 0.20.1 (appimg)

**Comment by lorenzncode** [comment]
What settings are defined in FreeCAD Import preferences?

Open Preferences to view the STEP Import settings:
Edit->Preferences...
Select Import-Export
Select STEP tab

With the default  STEP import settings I have: 
![image](https://user-images.githubusercontent.com/16394272/208249380-2b970f45-896f-4b93-b380-f76f38ff7c1f.png)

**Comment by tommy3001** [comment]
Got it.  

You have to load dependent workbenches additionally before access to some extended preferences. Here, the step import preferences are only visible when part workbenches are loaded before. After loading, everything was working fine. 

![image](https://user-images.githubusercontent.com/538947/208250251-bc67d60c-c59c-4d71-b585-81697b08f49e.png)
