### ISSUE TITLE
Mating surfaces around a central point/axis

### ISSUE THREAD

**Issue by alikureishy** [CadQuery/cadquery#1214]
Say I am using an external ```parts()``` function that produces 3 dimensionally matched component ```Workplane``` objects : ```base```, ```left_cradle``` and ```right_cradle```, as shown below:

**Base**: (Actual orientation and position of the retrieved workplane might be different)
<img width="486" alt="Screenshot 2022-12-27 at 2 07 18 PM" src="https://user-images.githubusercontent.com/1193219/209726671-4d276ac7-5e77-4455-80be-ab696dac5b63.png">

**Left Cradle**: (Actual orientation and position of the retrieved workplane might be different)
<img width="472" alt="Screenshot 2022-12-27 at 2 06 51 PM" src="https://user-images.githubusercontent.com/1193219/209726686-b61ad9fc-5566-4c8a-aad8-0cdfe8ca0762.png">

**Right Cradle**: (Actual orientation and position of the retrieved workplane might be different)
<img width="531" alt="Screenshot 2022-12-27 at 2 07 05 PM" src="https://user-images.githubusercontent.com/1193219/209726682-3892ae08-34b2-4693-9177-07b4705cdc16.png">

Using the ```Assembly``` class, I want to mate the above objects together as shown below:
<img width="627" alt="Screenshot 2022-12-27 at 2 05 24 PM" src="https://user-images.githubusercontent.com/1193219/209726481-f050e9fa-e135-4621-9cd0-644c59b6a766.png">

A ***sample*** ```parts()``` function to generate those 3 sub-objects is:
```
def parts() -> Tuple[cq.Workplane, cq.Workplane, cq.Workplane]:
  outer_diameter: float = 40
  inner_diameter: float = 20
  cradle_length: float = 50
  base_length: float = 10

  cradle = (
      cq.Workplane()
      .circle(radius=outer_diameter/2)
      .circle(radius=inner_diameter/2)
      .extrude(until=cradle_length)
  )
  split_cradle = (
      cradle
      .workplane()
      .transformed(
          rotate=(0, 90, 0),
          offset=(0, 0, 0),
      )
      .split(keepTop=True, keepBottom=True)
  )
  
  # 3 produced sub-parts:
  right_cradle = split_cradle.item(0)
  left_cradle = split_cradle.item(1)
  base = (
      cq.Workplane()
      .circle(radius=outer_diameter/2)
      .extrude(until=base_length)
  )
  return (base, left_cradle, right_cradle)
```

**I attempted to assemble the ```base```, ```left_cradle``` and ```right_cradle``` together using the following assembly code:**
```
base, left_cradle, right_cradle = parts()

assembly = (
    cq.Assembly()
    .add(left_cradle, name="left_cradle")
    .add(right_cradle, name="right_cradle")
    .add(base, name="base")
    
    # Constraints
    .constrain(
        "left_cradle", 
        left_cradle.faces(">X").faces(">Y").val(), 
        "right_cradle", 
        right_cradle.faces(">X").faces(">Y").val(),
        "Axis",
        param=pi
    )
    .constrain(
        "left_cradle", 
        left_cradle.faces(">X").faces("<Y").val(), 
        "right_cradle", 
        right_cradle.faces(">X").faces("<Y").val(),
        "Axis",
        param=pi
    )
    .constrain(
        "base", 
        base.faces(">Z").val(), 
        "right_cradle", 
        right_cradle.faces("<Z").val(),
        "Axis",
        param=pi
    )
    .constrain(
        "base", 
        base.faces(">Z").val(), 
        "left_cradle", 
        left_cradle.faces("<Z").val(),
        "Axis",
        param=pi
    )
    .solve()
)
```

... but instead of getting a tightly mated object (illustrated at the top), I get this below:
<img width="493" alt="Screenshot 2022-12-27 at 2 18 43 PM" src="https://user-images.githubusercontent.com/1193219/209727439-c268cda6-2324-4ff3-8737-007847dfac1c.png">

I know I need a couple more constraints, but I can't figure out what they should be. Since I don't have access to any information within the ```parts()``` method, I don't have any of the measurements to use as offsets etc. All I have are the ```Workplane``` instances, and I'd like to use the simplest approach possible to assemble them together.

How would I go about this? Code would be great. Thanks in advance.

**Comment by lorenzncode** [comment]
Here is one approach you might try:

```py
assembly = (
    cq.Assembly()
    .add(left_cradle, name="left_cradle")
    .add(right_cradle, name="right_cradle")
    .add(base, name="base")
)

assembly.constrain("left_cradle", "Fixed")

assembly.constrain(
    "right_cradle@faces@>Z",
    "FixedAxis",
    (0, 0, 1),
)

assembly.constrain(
    "left_cradle@faces@>XY",
    "right_cradle@faces@<X and >Y",
    "Plane",
)

assembly.constrain("base@faces@>Z", "left_cradle@faces@<Z", "Axis")

v0 = left_cradle.vertices(">X and <YZ")
v1 = left_cradle.vertices(">XY and <Z")
e0 = cq.Edge.makeLine(v0.val().toTuple(), v1.val().toTuple())
assembly.constrain(
    "base",
    base.faces(">Z").val(),
    "left_cradle",
    e0,
    "Point",
)


assembly.solve()

show_object(assembly)
```

**Comment by alikureishy** [comment]
Thanks @lorenzncode ! That worked!
