### ISSUE TITLE
Example for revolve provides 3-tuples but links to revolve doc saying 2-tuples for axis of rotation

### ISSUE THREAD

**Issue by jabowery** [CadQuery/cadquery#1221]
An example for revolve provides 3-tuples:
![image](https://user-images.githubusercontent.com/57646/211693973-b55a6df5-9de2-4854-a972-d395cb23ef4c.png)
but [the document says to use 2-tuples](https://cadquery.readthedocs.io/en/latest/classreference.html?highlight=revolve#cadquery.Workplane.revolve):

```
axisStart (tuple, a two tuple) – the start point of the axis of rotation

axisEnd (tuple, a two tuple) – the end point of the axis of rotation
```

**Comment by lorenzncode** [comment]
Also see #1125.  In this case I would probably remove the type field in the docstring.

**Comment by lorenzncode** [comment]
The docstrings/docs have been updated.  The type hints are displayed in both the signature and the parameter list.
