### ISSUE TITLE
Arc approximation

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#1230]
In OCCT 7.7 it is possible to use `BRepAlgo::ConvertWire` to convert arbitrary wires to arc splines. Possible applications include simplified DXF export, better SVG export and genric (approimate) hull.

Links to OCCT documentation:
*  https://github.com/Open-Cascade-SAS/OCCT/blame/526c506cb0a6a5c9c168ab5efd0a4e5211e30bf4/src/BRepAlgo/BRepAlgo.cxx#L83
* https://dev.opencascade.org/doc/refman/html/class_b_rep_algo.html#afe919c70d6b746ec02b320196a59a97d

**Comment by lorenzncode** [comment]
This was implemented in #1226 and so far applied to DXF export.

**Comment by adam-urbanczyk** [comment]
Thanks, closing
