### ISSUE TITLE
Version reported as 0.0.0 for dev versions when using conda or pip

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/cadquery#1252]
```
>>> import cadquery
>>> cadquery.__version__
'0.0.0'
```

**Comment by lorenzncode** [comment]
This is true at least for master.

Perhaps #1245 will correct the version for the release but then does it go back to 0.0.0 for master?

**Comment by jmwright** [comment]
@lorenzncode Maybe it's related to the environment variable mentioned in #1085 ? Start [here](https://github.com/CadQuery/cadquery/pull/1085#issuecomment-1138674053) and ready the previous few comments to get the context.

**Comment by lorenzncode** [comment]
@jmwright Thanks, I see it's set here with build variable `Build.SourceBranchName`.

https://github.com/CadQuery/conda-packages/blob/40f77ee43585a70e5958f6d7890e793337630ce1/conda-build.yml#L71

**Comment by adam-urbanczyk** [comment]
This is not a "when installing with conda" issue, but rather "when installing a dev version" issue.

Release version for at least 2.2 reports `__version__` correctly.
