### ISSUE TITLE
extrude face from sketch

### ISSUE THREAD

**Issue by mukral** [CadQuery/cadquery#1264]
Hi,
I can't get a face extruded when the origin is a sketch and not a workplane.
Error is: 'Sketch' object has no attribute 'toPending'
Is there any possibility to make the code below run?
```
import cadquery as cq

result1 = (
    cq.Workplane("XY")
    .box(2.0, 2.0, 0.5)
    .faces(">Z").wires().toPending().extrude(.5)
)
show_object(result1)
object1 = cq.Sketch().segment((0.,0),(0.,2.)).segment((2.,0)).close().assemble()
show_object(object1)
result2 = object1.faces(">Z").wires().toPending().extrude(.5)
show_object(result2)
```
Thank you for support.
Markus

**Comment by adam-urbanczyk** [comment]
Read through this section of the docs https://cadquery.readthedocs.io/en/latest/sketch.html#workplane-integration. You need to place the sketch on a workplane.
