### ISSUE TITLE
Eliminate level of hierarchy Assembly export

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/cadquery#1266]
Assembly STEP export currently creates a root node with hardcoded name "CQ assembly". 

![image](https://user-images.githubusercontent.com/16394272/217988310-efee15f3-5f01-4f8a-863f-6bbac22b52a8.png)

(from #1239 code with unsupported constraint removed)

This root node could be considered extraneous and be removed.
![image](https://user-images.githubusercontent.com/16394272/217988769-126779a7-19f9-48ee-9e89-aabfaea8bd06.png)

Regarding the root name,  I think the existing naming can be used here - the user specifies a name else it is auto generated uuid.

**Comment by jmwright** [comment]
@lorenzncode What is the advantage of using UUID over a default of "CQ assembly"? It's it just to avoid naming collisions, or are there other reasons?

What module/method should be used to generate the UUID?

**Comment by lorenzncode** [comment]
@jmwright A name may optionally be provided when creating an assembly. 

```py
assy = cq.Assembly(name = "myassy")
```

If a name is not given, a UUID is automatically assigned as the name.
https://github.com/CadQuery/cadquery/blob/0aa889cdcb4598d22da304d94efc28befeecb423/cadquery/assembly.py#L118

PR #1270 removes the extraneous top level node that had been created on STEP export.  Now that the root node is an assembly, the assembly name itself can be used.  Changing the name to a different hard coded default would require additional logic.  I didn't see the value of adding special handling to change the name from the UUID to say "CQ Assembly" if a name was not given.

For PR #1261, could you access the existing Assembly `name` property rather than add a separate interface with `assembly_name`?

**Comment by jmwright** [comment]
> For PR https://github.com/CadQuery/cadquery/pull/1261, could you access the existing Assembly name property rather than add a separate interface with assembly_name?

Yes, it should have been done that way but I forgot about being able to specify a name for the assembly. I'll work on making that change and using a UUID for when the name is not specified.
