### ISSUE TITLE
cadquery is back on conda-forge

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#1281]
Latest cq release is available again via the conda-forge channel. (https://github.com/conda-forge/cadquery-feedstock/):
```
mamba install -c conda-forge cadquery
```

This also implies that It should be possible now to install cq on apple silicon. It would be great though, if someone could verify this claim.

**Comment by jmwright** [comment]
@bernhard-42 Reported on Discord that it works well on an M1 Mac.
