### ISSUE TITLE
Update version in Sphinx `conf.py`

### ISSUE THREAD

**Issue by sethfischer** [CadQuery/cadquery#1283]
The version and release used by Sphinx is set to `1.0` and `1.0.0` respectively.

Update to reflect that the docs are for CadQuery 2.

```python
# doc/conf.py

# The short X.Y version.
version = "1.0"
# The full version, including alpha/beta/rc tags.
release = "1.0.0"
```

One place I have seen this version used is links generated with [sphinx.ext.intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html). The intersphinx link title is set to "(in CadQuery v1.0)" and is displayed on hover.

**Comment by jmwright** [comment]
@sethfischer Would you be interested in putting a PR together to change this?
