### ISSUE TITLE
README expand on Jupyter usage 

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/cadquery#1290]
The README states:
_CadQuery supports Jupyter notebook out of the box using the jupyter-cadquery extension_

The above is misleading, because as of 2.2.0, CadQuery works with Jupyter out of the box (does not require any extension for it).

Basic display in Jupyter works without using any other extensions.  I'd propose to mention the built-in support for Jupyter in the README as long as the README contains a section on Jupyter.

**Comment by adam-urbanczyk** [comment]
Good catch, the quoted statement does not make sense.

**Comment by RebelYoung** [comment]
hello, in my windows 10 pc, when I used jupyter by *.ipynb  in vscode or pycharm,and cadquery version is 2.5.2. It can not show the figure inline. A vtkOutput window always jumps up but no any figure in it. How to figure out?

<img width="922" height="850" alt="Image" src="https://github.com/user-attachments/assets/3ce48abe-f533-4a7d-a942-f23ddd5440a0" />

<img width="900" height="700" alt="Image" src="https://github.com/user-attachments/assets/07ce14b2-7669-42df-adc6-c27a9e5ab239" />

This is your example:

<img width="677" height="429" alt="Image" src="https://github.com/user-attachments/assets/3112687a-57a8-4559-a13a-276b0c952bb7" />
