### ISSUE TITLE
GMSH integration

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#1346]
With OCP 7.7.1 it should be possible to import OCCT shapes from memory
```python
import cq
import gmsh

gmsh.initialize()

gmsh.model.occ.importShapesNativePointer(cq.Workplane().box(1,1,1).val()._address())
```

- [x] Check if it actually works

**Comment by shimwell** [comment]
Running the above (recently updated) script works over here..
![Screenshot from 2023-06-13 22-41-49](https://github.com/CadQuery/cadquery/assets/8583900/8fce875c-bb69-45f4-bcc7-d235094782dc)

**Comment by shimwell** [comment]
When exporting workplanes that have surfaces in contact it is nice to merge those surfaces together. This allows the meshing to be conformal at the surface boundary between the two workplanes.

I think this code does the same as above but works for two workplanes that contact on a surface.

```python
import cadquery as cq
import OCP
import gmsh

workplane1 = cq.Workplane("XY").cylinder(height=10, radius=4)
workplane2 = cq.Workplane("XY").cylinder(height=10, radius=5).cut(workplane1)

cq.exporters.export(workplane1, "workplane1.step")
cq.exporters.export(workplane2, "workplane2.step")

bldr = OCP.BOPAlgo.BOPAlgo_Splitter()

bldr.AddArgument(workplane1.val().wrapped)
bldr.AddArgument(workplane2.val().wrapped)

bldr.SetNonDestructive(True)

bldr.Perform()

bldr.Images()

merged_surface_compound = cq.Compound(bldr.Shape())

# it looks like cq.Compound does not have a toOCC method like cq.workplane does
# however it has a val().wrapped which returns a OCP.TopoDS.TopoDS_Solid
topods = merged_surface_compound.wrapped

gmsh.initialize()
gmsh.option.setNumber("General.Terminal", 1)
volumes = gmsh.model.occ.importShapesNativePointer(topods._address())
gmsh.model.occ.synchronize()
gmsh.option.setNumber("Mesh.Algorithm", 1)
gmsh.option.setNumber("Mesh.MeshSizeMin", 20)
gmsh.option.setNumber("Mesh.MeshSizeMax", 30)
gmsh.model.mesh.generate(2)
gmsh.write("gmsh_of_cadquery_compound_in_memory.msh")
```

I shall confirm if this works or not soon

**Comment by shimwell** [comment]
Confirming that the surface merge and mesh worked

As we can see from this screenshot the resulting gmsh has just 6 surfaces instead of the 7 surfaces made in cadquery because the contact surface has been merged
![Screenshot from 2023-06-14 20-51-07](https://github.com/CadQuery/cadquery/assets/8583900/23f5f92d-3fe6-462f-8278-27473a658d4b)

**Comment by adam-urbanczyk** [comment]
Great! Thanks for the investigation @shimwell .
