### ISSUE TITLE
Offline version of documentation (zipped HTML)

### ISSUE THREAD

**Issue by fe60** [CadQuery/cadquery#1352]
Without or with a poor internet connection it would be helpful to have an offline version of the documentation.
Please consider generating a downloadable zipped HTML.

https://docs.readthedocs.io/en/stable/downloadable-documentation.html
https://docs.readthedocs.io/en/stable/guides/enable-offline-formats.html

**Comment by juhldesign** [comment]
I am going to second this, read the docs offers a pdf export but it appears to be disabled for CadQuery

**Comment by jmwright** [comment]
I'm reopening this issue even though the PR closed it. There is still more work to be done. The dynamic renders are ignored in the PDF and epub versions. The zipped HTML seems to work as expected though.
