### ISSUE TITLE
Regression in the CI pipline - package is not uploaded

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#1363]
Please do not merge anything until this is fixed

**Comment by adam-urbanczyk** [comment]
For some reason the pipeline installs much older versions of mamba/boa which seems to cause the issue.

**Comment by adam-urbanczyk** [comment]
Fixed here: https://github.com/CadQuery/conda-packages/blob/master/conda-build.yml

**Comment by jmwright** [comment]
Thanks @adam-urbanczyk
