### ISSUE TITLE
Extrude with taper on any Workplane return a wrong extrude length

### ISSUE THREAD

**Issue by trunglebao** [CadQuery/cadquery#1383]
Generic use of the extrude(until = x, taper = y) command will result in extrude length less than x.

```
a = list(range(0,60))
z = []
for angle in a:
    part = cq.Solid(cq.Workplane('XY').rect(1,1).extrude(1, taper = angle).toOCC())
    bb = part.BoundingBox()
    z.append(bb.zlen)
```

Running the code above create a bunch of extrude with height 1, with taper ranging from 0 to 60 degree.
Plotting the taper angle (0 to 60 degree) with resulted extrude height (suppose to be 1):
![image](https://github.com/CadQuery/cadquery/assets/141016295/f756027d-d777-45c7-9940-6175798f69f3)

Only taper = 0 return the correct height = 1, the rest is all less than 1.
Any thought/alternative solution to get the correct height?
Thanks!

**Comment by trunglebao** [comment]
That explained it. Thank you very much!
Most of the CAD software that i use set the extrude length to be zlen regardless of the taper amount. While cq use the length of the tapered edge.

![image](https://github.com/CadQuery/cadquery/assets/141016295/2abda24f-7e61-4e3f-b1f3-e427ec3a5db6)

Regardless, very useful library. Hat off to you guys.

**Comment by adam-urbanczyk** [comment]
I think we need to fix this. Me expectation was that this param is height, that is confirmed by the docstring:
```
The distance to extrude, normal to the workplane plane
```

**Comment by jmwright** [comment]
@trunglebao This has been fixed in the latest commit, (see linked PR) but the CI system will need a few hours to build and deploy.
