### ISSUE TITLE
Support configuring console output verbosity

### ISSUE THREAD

**Issue by ubruhin** [CadQuery/cadquery#1397]
Currently the console output is quite verbose, at least when performing a STEP export. To avoid the "noise" on the console output, we would like to configure the logging level.

I found out that this is possible by accessing OCP directly:

```python
from OCP.Message import Message, Message_Gravity

for printer in Message.DefaultMessenger_s().Printers():
    printer.SetTraceLevel(Message_Gravity.Message_Fail)
```

So this is not a critical issue at all, but I think it would be nice to have this feature in the API of CadQuery.

Links to OCCT documentation:
*  [`Message::DefaultMessenger()`](https://old.opencascade.com/doc/occt-7.5.0/refman/html/class_message.html#ad0c5aeb130d818b04fc5cdab47219413)
* [`Message_Messenger::Printers()`](https://old.opencascade.com/doc/occt-7.5.0/refman/html/class_message___messenger.html#a079c3ec4453b4f3cbb34a7a8f004cc2a)
* [`Message_Printer::SetTraceLevel()`](https://old.opencascade.com/doc/occt-7.5.0/refman/html/class_message___printer.html#a86714717ca708e6d0b5ddacbe073c7b3)

**Comment by adam-urbanczyk** [comment]
How about simply setting the level to `Message_Gravity.Message_Fail` in CQ without adding new methods?
