### ISSUE TITLE
Set glTF export format automatically based on .gltf or .glb file extension

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/cadquery#1419]
Blender example:

![blender_file_export_gltf](https://github.com/CadQuery/cadquery/assets/16394272/229012c9-7113-4c80-9207-6cc6598771ef)

Format is selected in the _Format_ drop-down list, for JSON:

![blender_gltf](https://github.com/CadQuery/cadquery/assets/16394272/75a06963-6b77-4841-b6ad-1b9a33d30ee6)

Note that the file extension is updated automatically based on the format selection.

Binary:

![blender_glb](https://github.com/CadQuery/cadquery/assets/16394272/50edb1d3-c486-4c45-a2d0-4dfcf28e2709)

FreeCAD example:
![freecad_gltf](https://github.com/CadQuery/cadquery/assets/16394272/e5d327cd-0542-4540-9988-f1a4c9420757)

Export format is determined based on the file extension.
```
$ file PartDesignExample-Body.*
PartDesignExample-Body.bin:  data
PartDesignExample-Body.glb:  glTF binary model, version 2, length 18528 bytes
PartDesignExample-Body.gltf: JSON text data
```

Current cadquery behavior:

The following results in a binary glTF (good - as expected).
```py
cq.exporters.assembly.exportGLTF(assy, "assy.glb")
```

This also results in a binary glTF (not expected).
```py
cq.exporters.assembly.exportGLTF(assy, "assy.gltf")
```

I'd propose to change `exportGLTF` to respect the convention of the file extension regarding output format.  The `binary` parameter can then apply only to the cases where the file extension is unknown.

Proposed change, this would export JSON text data glTF:
```py
cq.exporters.assembly.exportGLTF(assy, "assy.gltf")
```

Export binary glTF:
```py
cq.exporters.assembly.exportGLTF(assy, "assy.glb")
# or
cq.exporters.assembly.exportGLTF(assy, "assy.customextension")
```

Export JSON text data glTF:
```py
cq.exporters.assembly.exportGLTF(assy, "assy.customextension", False)
```

**Comment by jmwright** [comment]
Fixed in #1418
