### ISSUE TITLE
macOS M1, Python 3.10, ModuleNotFoundError: No module named 'OCP'

### ISSUE THREAD

**Issue by fferri** [CadQuery/cadquery#1444]
Not sure this is a duplicate of #590.

I am on macOS 13 arm64 and want to install cadquery with pip.

According to https://cadquery.readthedocs.io/en/latest/installation.html#install-via-pip 3.10 is the maximum Python version supported, so I installed python3.10 (via homebrew), then `python3.10 -m pip install ocp cadquery` (installed versions 0.1.9 and 2.3.0 respectively).

Then I run a cadquery script, but it fails:

```
$ python3.10 somescript.py
Traceback (most recent call last):
  File "somescript.py", line 1, in <module>
    import cadquery as cq
  File "/opt/homebrew/lib/python3.10/site-packages/cadquery/__init__.py", line 10, in <module>
    from .occ_impl.geom import Plane, BoundBox, Vector, Matrix, Location
  File "/opt/homebrew/lib/python3.10/site-packages/cadquery/occ_impl/geom.py", line 5, in <module>
    from OCP.gp import (
ModuleNotFoundError: No module named 'OCP'
```

**Comment by jmwright** [comment]
@fferri M1 Mac is not supported by Python wheel yet. Conda should work though.

https://github.com/CadQuery/ocp-build-system/issues/11
