### ISSUE TITLE
polyline is not correct, wrong position of first point

### ISSUE THREAD

**Issue by yguel** [CadQuery/cadquery#147]
Look at the code below:

```
import cadquery as cq
d0 = 17.25
h1 = 25

tri_z_min = 0
tri_O = (4,tri_z_min)
tri_A = (-2*d0,tri_z_min)
tri_B = (tri_A[0],2.25*h1)

tri_plane = cq.Plane( cq.Vector(0,d0,0),cq.Vector(1,0,0),cq.Vector(0,-1,0) )

pts = [ tri_O, tri_A, tri_B ]
cut_block = cq.Workplane(tri_plane).polyline(pts).close().extrude(2*d0)

show_object(cut_block)
```

The prism rightmost edge should have x coordinates equal to 4, but it is 0. It looks like the Workplane coordinate system and the polyline definition have been messed-up.

**Comment by adam-urbanczyk** [comment]
It is an interesting issue. If you inspect the stack in CQ-editor it seems that the `close()` command does not work properly:
![obraz](https://user-images.githubusercontent.com/13981538/59568624-96fd3880-907d-11e9-9b41-aa1d0166f0d4.png)

**Comment by adam-urbanczyk** [comment]
This is the root cause:
https://github.com/CadQuery/cadquery/blob/ef0808f4104e7c82da5df0e66355da0f3bbd24af/cadquery/cq.py#L1915

I am not sure if this is a bug or a feature, any thoughts @dcowden @jmwright ?

@yguel  workaround for now: move the center to the first point and then us `polyline`.

**Comment by jmwright** [comment]
I think that this has caused confusion before, so I'm ok changing it as long as all the tests still pass. Hopefully there's not some edge case that this will break that are not covered in the tests.
