### ISSUE TITLE
What does question marks(?)(in assebly's constrain function) mean?

### ISSUE THREAD

**Issue by huskier** [CadQuery/cadquery#1473]
In document's PointInPlane example, there is the following code. What does question marks(?)(in assebly's constrain function) mean? 

```
# constrain the bottom of the box to be on the plane defined by inner_horiz:
assy.constrain("box@faces@<Z", "bracket?inner_horiz", "PointInPlane")
# constrain the side of the box to be 0.2 units from the plane defined by inner_vert
assy.constrain("box@faces@<Y", "bracket?inner_vert", "PointInPlane", param=0.2)
```

**Comment by adam-urbanczyk** [comment]
`?name` refers to the tagged item `name`. This should be stated explicitly in the docs.

**Comment by huskier** [comment]
Thank you @adam-urbanczyk.
And then "bracket?inner_horiz" means "bracket's ?inner_horiz" literally?

**Comment by adam-urbanczyk** [comment]
Indeed. Obviously it assumes that `inner_horiz` was tagged.

**Comment by huskier** [comment]
Thanks.
