### ISSUE TITLE
Could we use show_object(...) function to show the 3D models in CLI?

### ISSUE THREAD

**Issue by huskier** [CadQuery/cadquery#1486]
At present, I've installed version 2.3.1, and I cannot use show_object() function to show 3D models. I've found that the VTK render was committed after the version 2.3.1. So I wonder whether we could use show_object(...) function to show the 3D models in CLI without CQ-editor and Juptylab notebook?

**Comment by jmwright** [comment]
You'll have to wait for this month's release unless you want to install from git/conda-master, but you can use the following.
```python
from cadquery.vis import show
result = ...
show(result)
```
If you wanted consistent naming, you could also do:
```python
from cadquery.vis import show as show_object
```

**Comment by huskier** [comment]
Thanks.
