### ISSUE TITLE
Workplane.union error with None

### ISSUE THREAD

**Issue by aavogt** [CadQuery/cadquery#1536]
I use the following instead of `union`:

```python
import cadquery as cq
cq.Workplane.union2 = lambda self, x: x is None and self or self.union(x)
```
This avoids a `ValueError: Cannot union type '<class 'NoneType'>'`. `cq.Workplane().union(None)` makes that exception. The type hint says that union(None) should work.

I use it to share code for two similar parts:
```python
def mkresult(withBase=True):
    return (cq.Workplane("XY").circle(68).extrude(2)
        .union2(withBase and base or None)
        ....
```

**Comment by jmwright** [comment]
The type hint is misleading in this case. It looks like only [Workplane](https://github.com/CadQuery/cadquery/blob/3451007f8eeb9d78e784ec8047ef69a5359ecb5e/cadquery/cq.py#L3364) and [Solid/Compound](https://github.com/CadQuery/cadquery/blob/3451007f8eeb9d78e784ec8047ef69a5359ecb5e/cadquery/cq.py#L3371) are accepted in the code.
