### ISSUE TITLE
Is it possible to get a dummybox's center.x, center.y, and center.z?

### ISSUE THREAD

**Issue by huskier** [CadQuery/cadquery#1554]
I want to use a dummybox's center(CenterOfBoundBox) to make a dummy vertex, and I've tagged the box with "dummybox".
```
mybox = cq.Workplane().box(60, 10, 50, centered=True).tag("dummybox").end()
```
However, I don't know how to use the "dummybox" tag to get it's center.x, center.y and center.z in assembly constrain. The center here means the center of BoundBox.

**Comment by adam-urbanczyk** [comment]
Are you looking for this: `assy.constrain(..., "mybox_name?dummybox",...)`? If so, take a look at the assy tutorial: [constraints-definition](https://cadquery.readthedocs.io/en/latest/assy.html#constraints-definition).

**Comment by huskier** [comment]
@adam-urbanczyk Thank you for your quick reply, Adam.

I've understood the materials you pointed, and I've tried "mybox?dummybox". The Python interpret gives the following error 
> KeyError: 'mybox?dummybox'

Actually, my object is to constrain 3D text with the help of BoundBox. My code is as following. At present, I use mybox1 to help me to make the dummy vertex. But it is not possible for further assembly. What I want is to use the tagged "dummybox".
```
import cadquery as cq
from cadquery.vis import show

text_string = "CadQuery"
font = "Arial"
size = 10
text3D = cq.Workplane("XZ").text(text_string, font=font, fontsize=size, distance=2)

xlen = text3D.val().BoundingBox().xlen
ylen = text3D.val().BoundingBox().ylen
zlen = text3D.val().BoundingBox().zlen

mybox = cq.Workplane().box(xlen, ylen, zlen, centered=True).tag("dummybox").faces("<Y").tag("boxY_Negtive").end().faces("<Z").tag("boxZ_Negtive").end(2)  #.translate(text3DCenter)
mybox1 = cq.Workplane().box(xlen, ylen, zlen, centered=True)

asm = cq.Assembly(name="TextOnPanel")
asm.add(text3D, color=cq.Color(1, 0, 0), name="text3D")
asm.add(mybox, color=cq.Color(0, 0, 1), name="mybox")

text3DCenter = text3D.val().BoundingBox().center
myboxCenter = mybox1.val().BoundingBox().center

(
    asm
    .constrain("text3D@faces@>Y", "mybox?boxY_Negtive", "Axis")
    .constrain("text3D@faces@>Z[-1]", "mybox?boxZ_Negtive", "Axis")    
    .constrain("text3D", cq.Vertex.makeVertex(text3DCenter.x, text3DCenter.y, text3DCenter.z), "mybox?dummybox", cq.Vertex.makeVertex(myboxCenter.x, myboxCenter.y, myboxCenter.z), "Point") 
)
asm.solve()
show(asm)
```

**Comment by adam-urbanczyk** [comment]
Did you mean:
```
(
    asm
    .constrain("text3D@faces@>Y", "mybox?boxY_Negtive", "Axis")
    .constrain("text3D@faces@>Z[-1]", "mybox?boxZ_Negtive", "Axis")    
    .constrain("text3D", "mybox?dummybox", "Point") 
)
```

**Comment by huskier** [comment]
Simple, Beautiful! Yes, that's what I want. I'm so obsessed with the CQ's assembly system. Thank you, Adam. @adam-urbanczyk
