### ISSUE TITLE
Documentation: Assembly tutorial constraint solver result regression

### ISSUE THREAD

**Issue by Roger-random** [CadQuery/cadquery#1585]
As a CadQuery beginner I've been hanging out in documentations. I noticed a regression in the Assemblies documentation page introduced sometime in the past week(-ish) timeframe. Every constraint solver result shown in the 3D viewer seems to have gone awry. GitHub says the documentation page source (https://github.com/CadQuery/cadquery/blob/master/doc/assy.rst) has not been touched in four months. I don't know where to look next.

URL: https://cadquery.readthedocs.io/en/latest/assy.html

### Expected: layout to match the static screenshot (repeated here for easy reference)

![door_assy_freecad](https://github.com/CadQuery/cadquery/assets/8559196/b8a814d1-d4e2-4d3a-9e9c-cedc0d9d1180)

### Actual: layout now looks like this.

![cadquery assemblies documentation solver error](https://github.com/CadQuery/cadquery/assets/8559196/be245127-1e96-41c0-b962-be7df1221c8a)

### Environment

Verified on following browsers:
* Firefox 125.0.3
* Chrome 124.0.6367.202
* Edge 124.0.2478.80

OS: Windows 11

**Comment by adam-urbanczyk** [comment]
Thanks, looks like the free function PR did break something. AFAICT rendering assemblies locally works fine. I guess some kind of weird interaction between the cq directive and the new `cq.Location` constructors. I will look into it.

**Comment by lorenzncode** [comment]
I confirm local render with cq-editor or `cadquery.vis` works fine here.  I can reproduce the issue with a local sphinx doc build.

**Comment by lorenzncode** [comment]
`toTuple` was changed to return degrees.
https://github.com/CadQuery/cadquery/blob/995d1393bd3cba2061da7e7d2bea8e4fdbdd19c9/cadquery/occ_impl/geom.py#L1059

`toTuple` is called here in `toJSON` used in the cq directive:
https://github.com/CadQuery/cadquery/blob/995d1393bd3cba2061da7e7d2bea8e4fdbdd19c9/cadquery/occ_impl/assembly.py#L338

**Comment by adam-urbanczyk** [comment]
Yup, just opened a PR
