### ISSUE TITLE
How to calculate moment of inertia?

### ISSUE THREAD

**Issue by lenianiva** [CadQuery/cadquery#1605]
If I have an assembly where different parts have different colours, and each colours corresponds to a density, is there a way to calculate the MoI about a particular axis?

**Comment by bragostin** [comment]
I guess your question regarding CadQuery is how to get the volume of an object so that you can calculate the moment of inertia? That would be `cq_object.val().Volume()`

**Comment by lenianiva** [comment]
> I guess your question regarding CadQuery is how to get the volume of an object so that you can calculate the moment of inertia? That would be `cq_object.val().Volume()`

No I need to calculate the MoI of an assembly of objects with different densities. If the object is homogeneous I can just call `matrixOfInertia()`

**Comment by adam-urbanczyk** [comment]
You'll need to implement this yourself
