### ISSUE TITLE
Simple getting the coordinates of a point.

### ISSUE THREAD

**Issue by dimonbavly** [CadQuery/cadquery#164]
If I have, for example:
`cq.Workplane("XY") .box(1,1,1).faces(">Z").edges(">Y").vertices(">X") `
how can I get it coordinate?

**Comment by jmwright** [comment]
@dimonbavly You can do this:
```python
import cadquery as cq
x = cq.Workplane("XY") .box(1,1,1).faces(">Z").edges(">Y").vertices(">X").first().val().X
```
If you're using CQ-editor, you can view the value of x in the Variables inspector. It should show 0.5 because the box is centered around the origin. You should be able to use an iterator to step through all of the selected vertices.

**Comment by jmwright** [comment]
@dimonbavly Please reopen if you need more help.
