### ISSUE TITLE
Length of an edge

### ISSUE THREAD

**Issue by lenianiva** [CadQuery/cadquery#1641]
Is there a way to get the length for an `Edge` object? In particular I'm interested in the length of splines and bezier curves.

**Comment by adam-urbanczyk** [comment]
You can use `cq.Edge.Length`

**Comment by lenianiva** [comment]
> You can use `cq.Edge.Length`

I don't see that function here: https://github.com/CadQuery/cadquery/blob/3cd327a2dbaf3bae6791463a3dcb0ad7a714b607/cadquery/occ_impl/shapes.py#L1920. Where is it defined?

**Comment by adam-urbanczyk** [comment]
https://github.com/CadQuery/cadquery/blob/3cd327a2dbaf3bae6791463a3dcb0ad7a714b607/cadquery/occ_impl/shapes.py#L1760

**Comment by lenianiva** [comment]
> https://github.com/CadQuery/cadquery/blob/3cd327a2dbaf3bae6791463a3dcb0ad7a714b607/cadquery/occ_impl/shapes.py#L1760

Thanks. I didn't see it in the documentation so I was wondering about this

**Comment by adam-urbanczyk** [comment]
Yup, probably sphinx does not process mixins.
