### ISSUE TITLE
How to get the inner wires created by a rectangle and a circle?

### ISSUE THREAD

**Issue by huskier** [CadQuery/cadquery#1661]
As the following illustration, a rectangle and a circle created inner wires. How to get the inner wires with the CadQuery's Sketch operation?
![image](https://github.com/user-attachments/assets/fcf8deb5-04b3-4829-ae66-71a588ba1425)

I've found a method to get the inner wires by employing Workplane operations, but I think it is somewhat awkward. I'd like a method to get the inner wires by Sketch operations.

My approach is as following:

```
import cadquery as cq
from cadquery.vis import show

part1 = cq.Workplane().box(13.6, 15.1, 10)
part2 = part1.faces(">Z").circle(15.1/2).cutBlind(-5)
target_wire = part2.faces(">Z[-2]").wires()
show(target_wire)
```

**Comment by nobkd** [comment]
Isn't this just the **intersection** of a circle and a rectangle?

```py
wire = cq.Sketch().rect(13.6, 15.1).circle(15.1 / 2, 'i').wires()
```

**Comment by huskier** [comment]
Thank you, nobkd. @nobkd
