### ISSUE TITLE
do cskHole and cboreHole only work along z-axis?

### ISSUE THREAD

**Issue by bigfighter** [CadQuery/cadquery#1707]
This works like a charm: `cq.Workplane('XY').box(10, 10, 10).faces('>Z').cskHole(1, 2, 90)`
But when I switch to a different face, something peculiar happens:
![image](https://github.com/user-attachments/assets/32048225-08e0-4860-80b5-04e72e5678a3)
Same for `.cboreHole(1, 2, 2)` instead of `.cskHole(1, 2, 90)`
Is there a way to drill sideways?

No big deal, I can always union a cone and a cylinder (or two cylinders for countersunk), move them into position and subtract them.
But cboreHole/cskHole would be so much more convenient.

**Comment by jmwright** [comment]
@bigfighter You need to establish a workplane after selecting the face.

```python
import cadquery as cq

box = cq.Workplane().box(100, 100, 100)

box = box.faces(">Y").workplane().cskHole(10, 20, 90)

show_object(box)
```
![Screenshot from 2024-11-20 15-03-39](https://github.com/user-attachments/assets/db0415bf-132a-49c0-8ae8-d566eb02bdda)

**Comment by bigfighter** [comment]
beautiful, thank you!
