### ISSUE TITLE
Specify which corner to use

### ISSUE THREAD

**Issue by davidedelvento** [CadQuery/cadquery#1708]
This does what I want on one face

```python
a = Workplane("XY")
a = a.box(9, 20, 4)
a = a.faces(">Y")
a = a.box(4, 13, 4, centered=[1,0,0])
```

however I want it on the *other* face, so I try

```python
a = Workplane("XY")
a = a.box(9, 20, 4)
a = a.faces("<Y")
a = a.box(4, 13, 4, centered=[1,0,0])
```

but that uses the "wrong" corner of the box and it goes wrong. Using `centered=[1,1,0]` in this second instance makes it slightly less wrong.

I guess I can fix this by either translating or mirroring the second box (or the whole thing), but that's a pain to get the appropriate values (or mirror surface) right in a parametric correct way. Is there a cleaner way?

**Comment by lorenzncode** [comment]
Specify the `centerOption` as in this example.  The center of the sphere is the selected corner vertex.

```py
import cadquery as cq

a = cq.Workplane("XY")
a = a.box(9, 20, 4)
a = a.vertices(">X and <Y and >Z")  # or as: ">XZ and <Y"
a = a.workplane(centerOption="CenterOfMass")
a = a.sphere(1)
```

See also the docs example _Locating a Workplane on a vertex_.

**Comment by lorenzncode** [comment]
I suppose creating the workplane is not needed for simply adding the sphere or box.  You would typically create the new workplane say in the following scenario where you are building on a selected face and vertex:

```py
a = cq.Workplane("XY")
a = a.box(9, 20, 4)
a = a.faces("<Y").vertices(">XZ")
a = a.workplane(centerOption="CenterOfMass")
# now the plane normal is in -Y dir, with center at selected corner
a = a.circle(2).extrude(5)
```

**Comment by davidedelvento** [comment]
Thanks @lorenzncode 

Unless I am completely misunderstanding what you are suggesting in both comments, and the example you are referring (which I read before submitting the issue), this is not what I want. I am able to select the desired workplane just fine as in my examples. The problem is that the second box (the sphere in your example), is placed on that workplane using a vertex which is the one I want in the `>Y` case, but not the one I want in the `<Y` case. To be clearer, consider

```
a = Workplane("XY")
a = a.box(9, 20, 4)
a = a.faces(">Y")
a = a.box(4, 13, 4, centered=[1,0,1])
```

vs 

```
a = Workplane("XY")
a = a.box(9, 20, 4)
a = a.faces("<Y")
a = a.box(4, 13, 4, centered=[1,0,1])
```

The first is what I want but mirrored on the XZ plane (and without having to explicitly do that mirroring)

**Comment by davidedelvento** [comment]
I guess one possible solution is

```
a = Workplane("XY")
a = a.box(9, 20, 4)
a = a.faces(">Y")
a = a.workplane()
a = a.rect(4,4).extrude(13)
```

which works fine with both `>Y` and `<Y`

Is this the best option?

**Comment by lorenzncode** [comment]
OK I see, it could be done like this.  


```py
import cadquery as cq

# a, b are symmetric in XZ

a = cq.Workplane("XY")
a = a.box(9, 20, 4)
a = a.faces(">Y")
a = a.workplane(6.5)  # offset workplane in normal dir
a = a.box(4, 4, 13)

b = cq.Workplane("XY")
b = b.box(9, 20, 4)
b = b.faces("<Y")
b = b.workplane(6.5)  # offset workplane in normal dir
b = b.box(4, 4, 13)
```


I'd prefer your solution though to extrude the shape.

```py
a = a.workplane()
a = a.rect(4,4).extrude(13)
```

and then with this solution you can also use `Sketch`  when you have a more complex 2D shape to extrude.

```py
a = a.sketch().rect(4, 4).finalize().extrude(13)
```

**Comment by davidedelvento** [comment]
Got it thanks, and you also managed to let me start understanding sketches which have been puzzling me for a while!
