### ISSUE TITLE
how to use Workplane.text

### ISSUE THREAD

**Issue by Zawarud** [CadQuery/cadquery#178]
I need to see an example for add text on 3d model with :
`Workplane.text(txt, fontsize, distance[, …])`
how to use this command?

**Comment by jmwright** [comment]
There's an example in the test suite for CQ: https://github.com/CadQuery/cadquery/blob/master/tests/TestCadQuery.py#L1858

Documentation: https://cadquery.readthedocs.io/en/latest/classreference.html?highlight=text#cadquery.Workplane.text

**Comment by Zawarud** [comment]
Thanks. 
There are a metod to have always the text parallel to the view, if a rotate with mouse ?

**Comment by jmwright** [comment]
If you're using CQ-editor, you can hold down on the middle mouse button and drag to pan the object around. That will keep the text parallel if it was parallel to the view plane when you started panning.

**Comment by Zawarud** [comment]
im on jupyter lab. In this case how do this?

**Comment by jmwright** [comment]
@Zawarud I'm assuming you are using the jupyter-cadquery project? https://github.com/bernhard-42/jupyter-cadquery

@bernhardBV @bernhard-42 Are you able to answer the question above?

**Comment by Zawarud** [comment]
yes. jupyter-cadquery

**Comment by lalebarde** [comment]
Hi, could you push back the example please, the [link](https://github.com/CadQuery/cadquery/blob/master/tests/TestCadQuery.py#L1858) is dead

**Comment by nirvdrum** [comment]
A stable link is: https://github.com/CadQuery/cadquery/blob/2d721d0ff8a195a0902eb9c3add88d07546c05b1/tests/test_cadquery.py#L2701-L2750 I really wish GitHub didn't default to linking to "master".
