### ISSUE TITLE
Hole through drumbell fails

### ISSUE THREAD

**Issue by bragostin** [CadQuery/cadquery#179]
Something I don't understand. Why does this work
```python
path = cq.Workplane('XZ').moveTo(-2, 0).lineTo(2, 0)
pl = cq.Workplane('YZ').workplane(offset=-2).circle(5).workplane(offset=2).circle(1).workplane(offset=2).circle(5).sweep(path, multisection=True)
yzsh = [(1.25,1.25)]
pl = pl.faces('<X').workplane().pushPoints(yzsh).circle(5.5/2).extrude(-5).pushPoints(yzsh).hole(5.5-2*1.15, 4)
show_object(pl)
```
while this does not?
```python
path = cq.Workplane('XZ').moveTo(-2, 0).lineTo(2, 0)
pl = cq.Workplane('YZ').workplane(offset=-2).circle(5).workplane(offset=2).circle(1).workplane(offset=2).circle(5).sweep(path, multisection=True)
yzsh = [(1.5,1.5)]
pl = pl.faces('<X').workplane().pushPoints(yzsh).circle(5.5/2).extrude(-5).pushPoints(yzsh).hole(5.5-2*1.15, 4)
show_object(pl)
```
The only difference being that the hole center is 0.25 mm further away from the drumbell.

**Comment by jmwright** [comment]
@bragostin I experimented a little bit, and it seems like it could be a CAD kernel thing, but I'm not sure. It's going to require some deeper investigation.

**Comment by adam-urbanczyk** [comment]
It does seem like a CAD kernel issue. We should eventually update to OCCT 7.3, current kernel is really outdated.

**Comment by bragostin** [comment]
Interestingly, replacing the circle with a polygon works:
```python
path = cq.Workplane('XZ').moveTo(-2, 0).lineTo(2, 0)
pl = cq.Workplane('YZ').workplane(offset=-2).polygon(12, 10).workplane(offset=2).polygon(12, 2).workplane(offset=2).polygon(12, 10).sweep(path, multisection=True)
yzsh = [(1.5,1.5)]
pl = pl.faces('<X').workplane().pushPoints(yzsh).circle(5.5/2).extrude(-5).pushPoints(yzsh).hole(5.5-2*1.15, 4)
show_object(pl) 
```

**Comment by bragostin** [comment]
I am happy to report that OCP 7.4 solved this issue! 
The upgrade to OCP was also seamless: all my scripts still worked after the upgrade. Thank you for enabling OpenCascade 7.4 into CadQuery, a real work of art!

![error_drumbell_solved](https://user-images.githubusercontent.com/26216511/83557449-f6b05600-a511-11ea-834a-cef8cc1249d3.png)
