### ISSUE TITLE
Cadquery shouldn't install tests

### ISSUE THREAD

**Issue by l29ah** [CadQuery/cadquery#181]
Users don't need them, also Gentoo's build system is pissed:
```
 *   Package installs 'tests' package which is forbidden and likely a bug in the build system.
```

**Comment by adam-urbanczyk** [comment]
I never used Gentoo, so I am not sure how to interpret what you pasted. Are you referring to this line maybe?
https://github.com/CadQuery/cadquery/blob/b0b99599173e0eec952ed2e8381822217ed949d4/setup.py#L33

If so, it is indeed sub-optimal. I don't really agree with the broad statement that "cadquery shouldn't install tests" . We should probably move them to `cadquery.tests` though.

**Comment by l29ah** [comment]
Yeah, that's the problem it complains about.
