### ISSUE TITLE
Add the documentation website on top of the project's main page

### ISSUE THREAD

**Issue by Peque** [CadQuery/cadquery#193]
I would suggest putting `https://cadquery.readthedocs.io/` on top of the project's GitHub main page for easier/faster access.

See the "Edit" button on the bottom-right:

![Screenshot from 2019-09-16 21-53-20](https://user-images.githubusercontent.com/526577/64988755-776beb00-d8cc-11e9-8287-b5476437ed14.png)

I think it is a pretty common practice among projects. :blush:

**Comment by adam-urbanczyk** [comment]
Done, thanks.
