### ISSUE TITLE
How to convert STL to IGES [cad model] using Python? 

### ISSUE THREAD

**Issue by selvakarna** [CadQuery/cadquery#196]
How to convert STL to IGES [cad model] using Python?

**Comment by adam-urbanczyk** [comment]
I'm afraid that CQ does not support it. You could export from cadquery to STEP,  but there is not STL import (only STEP import is implemented). You'll be probably better off writing a python script for FreeCAD.

**Comment by selvakarna** [comment]
Hi ,@adam-urbanczyk  , is it any way to export cad from mesh or volume using python scripts?

**Comment by adam-urbanczyk** [comment]
There is no such functionality in CQ (due to lack of STL import).
