### ISSUE TITLE
2D / 3D convex hull

### ISSUE THREAD

**Issue by fi0** [CadQuery/cadquery#205]
Is there a function/macro that I can input a set of vertices, and output a surface?

**Comment by jmwright** [comment]
I don't think there is in the fluent API. @adam-urbanczyk or one of the other community members might know how to do it using PythonOCC.

**Comment by adam-urbanczyk** [comment]
We don't have that implemented @fi0 . If you are up to the challenge of implementing such functionality yourself, you could try looking at:
https://www.opencascade.com/doc/occt-6.9.1/refman/html/class_geom_plate___build_plate_surface.html
or
https://www.opencascade.com/doc/occt-6.9.1/refman/html/class_geom_a_p_i___points_to_b_spline_surface.html

**Comment by adam-urbanczyk** [comment]
It is implemented in #253 .
