### ISSUE TITLE
Bezier edge

### ISSUE THREAD

**Issue by fi0** [CadQuery/cadquery#206]
I can see there's an example for spline. Is there a helper function for bezier?

**Comment by adam-urbanczyk** [comment]
Nope, in principle you can achieve the same with splines. Do you have any specific use case?

**Comment by fi0** [comment]
I was trying to convert an SVG bezier path into CadQuery. I'll try splines.

**Comment by adam-urbanczyk** [comment]
I'll reopen - we'd like to have SVG import eventually.

**Comment by adam-urbanczyk** [comment]
Here is an example of using OCC api to prepare a 2D bezier:
https://github.com/CadQuery/rcad/blob/d814e0caee0d0ccc3ad4ec7fc92b9711a0c6ce95/ext/_rcad/_rcad.cpp#L920

**Comment by adam-urbanczyk** [comment]
@fi0 we have preliminary DXF import though without splines. It will be eventually extended with splines. DXF will likely receive more attention than SVG.

**Comment by adam-urbanczyk** [comment]
DXF import supports splines now - closing again.
