### ISSUE TITLE
Question: offset curve / tolerance

### ISSUE THREAD

**Issue by l4u** [CadQuery/cadquery#208]
I want to expand a 2D polyline surface by 1mm.
Similar to https://forum.freecadweb.org/viewtopic.php?t=9137

Or, is it on the roadmap?
https://cadquery.readthedocs.io/en/latest/roadmap.html#d-operations

**Comment by jmwright** [comment]
@l4u I think that's been on the roadmap since the early days of CQ 1.0 and we don't have it yet. More complex 2D operations and even 2D constraints are things we'd like to have. I'm hopeful that we'll eventually find a community member who's willing to lead that effort.

**Comment by adam-urbanczyk** [comment]
`Geom2d_OffsetCurve` seems to be the relevant function.

**Comment by l4u** [comment]
related: https://www.freecadweb.org/wiki/Part_Offset2D
