### ISSUE TITLE
Examples in the docs should use brackets rather than backslashes

### ISSUE THREAD

**Issue by abudden** [CadQuery/cadquery#221]
In all of the examples in the documentation, for example [the one here](https://cadquery.readthedocs.io/en/latest/quickstart.html#more-holes), backslashes are used for line continuation.

These should be changed to use brackets as it makes it **much** easier to add comments.  Compare:

```python
height = 60.0
width = 80.0
thickness = 10.0
diameter = 22.0
padding = 12.0

# make the base
result = cq.Workplane("XY").box(height, width, thickness)\
    .faces(">Z").workplane().hole(diameter)\
    .faces(">Z").workplane() \
    .rect(height - padding,width - padding,forConstruction=True)\
    .vertices()\
    .cboreHole(2.4, 4.4, 2.1)

# Render the solid
show_object(result)
```
with:
```python
height = 60.0
width = 80.0
thickness = 10.0
diameter = 22.0
padding = 12.0

# make the base
result = (cq.Workplane("XY").box(height, width, thickness)
    # Select the face on the top of the workpiece and make a hole in the middle
    .faces(">Z").workplane().hole(diameter)
    # Select the face on the top of the workpiece and draw a construction rectangle
    # with a border of 6 mm (padding/2) from each edge
    .faces(">Z").workplane() 
    .rect(height - padding,width - padding,forConstruction=True)
    # Get the vertices of the construction rectangle and draw a counterbored hole
    .vertices()
    .cboreHole(2.4, 4.4, 2.1)
    )

# Render the solid
show_object(result)
```

For what it's worth, this is from [PEP8](https://www.python.org/dev/peps/pep-0008/):

> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

**Comment by jmwright** [comment]
@abudden Thanks for pointing this out. It's something I had thought about, but never implemented. It's been merged.
