### ISSUE TITLE
extrude Does Not Respect Wire Selection

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery#241]
Noticed this while trying to help a user with a script. In the following line of code, the object returned after the `first` call is shown as expected, a single closed hexagonal wire.
```python
hexes1 = cq.Workplane("XY").pushPoints(pointsForHex).makeHex(diameterHex*1.0).wires().first()#.extrude(1)
```
![Screenshot from 2019-12-14 09-30-49](https://user-images.githubusercontent.com/1015439/70850089-6fcccb80-1e54-11ea-8a68-bc9fab6f5c4e.png)
However, once I uncomment the extrude, all the hex wires (the pointsForHex list had more than one point in it) are extruded, and not just the one I selected.
![Screenshot from 2019-12-14 09-33-18](https://user-images.githubusercontent.com/1015439/70850126-c934fa80-1e54-11ea-8c11-264dd65125b4.png)
It's stated in extrude's docstring that this behavior is expected: https://github.com/CadQuery/cadquery/blob/acf363d721377eb22cd39f16ce5718b9ff68f282/cadquery/cq.py#L2255

I'm probably forgetting some logic of why it is the way it is, but it seems like extrude should respect the current selection of wires, and not extrude everything.

Even if this should be changed, it seems like it would be easy to break existing scripts. Some thought/discussion will need to be put into it.

**Comment by adam-urbanczyk** [comment]
I did no come up with the design but I guess that `first()`, `last()` and `item(i)` are meant more for debugging than for construction. In other words: why would you first make an array of polygons and then select one to extrude it. You could just construct this single polygon in the first place.
