### ISSUE TITLE
CQ at FOSDEM 2020 - please share your success stories

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#242]
We will have a talk at FOSDEM 2020 in the Open Source Computer Aided Modeling and Design devroom. It would be great to show a slide with interesting models made by the users. Please share them here (preferably on white background)!

**Comment by Peque** [comment]
Toy project, but public... :wink:

I used it in a couple of pieces for a robot: [rim](https://bulebule.readthedocs.io/en/latest/building.html#rim), [mount](https://bulebule.readthedocs.io/en/latest/building.html#mounting).

**Comment by jmwright** [comment]
@adam-urbanczyk Thanks for taking this on. I hope they take a video of the presentation. I'm looking forward to seeing it.

@Peque Very cool! Thanks for sharing.

**Comment by jmwright** [comment]
[This project](https://opendesignengine.net/projects/yavin-thruster/wiki/Wiki) is from 2015, but I think it's kind of interesting. It used equations from a Jupyter notebook to drive the generation of a cold gas thruster nozzle using CadQuery (I coded the CadQuery model generation). The nozzle was then 3D printed for testing. A presentation was given in 2015 at the Open Hardware Summit, and I can check with the organization (Mach 30) to get a full resolution version of the diagram shown there if you want to include it.

**Comment by michaelgale** [comment]
I put this together a few weeks ago for the community's benefit.  Feel free to pull whatever assets you wish:
https://github.com/fx-bricks/fx-cad-notes

**Comment by dcowden** [comment]
@adam-urbanczyk thanks for participating in fosdem.

Doesn't Kicad  use Cadquery to build its model repo? I think it still uses cq 1.0

https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/QFN_packages

**Comment by jmwright** [comment]
> Doesn't Kicad use Cadquery to build its model repo? I think it still uses cq 1.0

Yes. It is still based on CQ 1.0 AFAIK.

**Comment by jmwright** [comment]
@easyw Can you comment on the above, please?

**Comment by bragostin** [comment]
I could share this Gyroïd surface
![gyroid](https://user-images.githubusercontent.com/26216511/71480704-da89e980-27fa-11ea-9e15-68ac2a3d7643.png)
but this is done with the Implementation of BRepOffsetAPI_MakeFilling #253 pull request, so that's not part of the master branch of CadQuery.

**Comment by adam-urbanczyk** [comment]
Cool @bragostin , could you share what is your application of CQ?

**Comment by bragostin** [comment]
@adam-urbanczyk these are cooling fins. Triply periodic surfaces are supposed to offer a better ratio of heat transfer over pressure drop.

**Comment by adam-urbanczyk** [comment]
I added some screenshots to the slides - thanks for your help @bragostin  @michaelgale @Peque @jmwright !
