### ISSUE TITLE
New CQ GUI available

### ISSUE THREAD

**Issue by dcowden** [CadQuery/cadquery#26]
<a href="https://github.com/adam-urbanczyk"><img src="https://avatars2.githubusercontent.com/u/13981538?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adam-urbanczyk](https://github.com/adam-urbanczyk)**
_Friday Jun 08, 2018 at 13:12 GMT_
_Originally opened as https://github.com/dcowden/cadquery/issues/280_

----

I made my CadQuery GUI public today. You can check it out here:

https://github.com/CadQuery/CQ-editor

![screenshot1](https://user-images.githubusercontent.com/13981538/41159853-327fcf6e-6b2e-11e8-9c07-44afb359fa18.png)

**Comment by dcowden** [comment]
<a href="https://github.com/zignig"><img src="https://avatars0.githubusercontent.com/u/109033?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zignig](https://github.com/zignig)**
_Friday Jun 08, 2018 at 13:29 GMT_

----

Nice work Adam. Will have a look and install it on my machine.

**Comment by adam-urbanczyk** [comment]
Closing this issue. Will add a link in the README.
