### ISSUE TITLE
Export to glTF

### ISSUE THREAD

**Issue by Peque** [CadQuery/cadquery#264]
Initially suggested in https://github.com/CadQuery/cadquery/issues/105.

JSON (I think that is what is known as `TJS` in CadQuery) is deprecated in Three.js, and other formats seem to be lossy formats or 2D formats (like SVG).

As @fragmuffin mentioned:

> `cqparts` also has a [GLTF exporter](https://cqparts.github.io/cqparts/doc/api/cqparts.codec.html#module-cqparts.codec.gltf), which is just awesome (GLTF I mean :wink:)

Maybe some code can be reused.

**Comment by Peque** [comment]
Advantages:

- Lossless (I think?)
- Multiple parts allowed
- Multiple colors/materials/textures

Maybe it could be used as the preferred intermediate format in CQ-editor GUI, `jupyter-cadquery`, `sphinx-cadquery`... I think it would be great if all those tools could share more code by using the same exporter/loader/visualizer. Or at least share as much as possible.

**Comment by adam-urbanczyk** [comment]
Yet another reason to update to a newer OCCT version: https://dev.opencascade.org/doc/refman/html/package_rwgltf.html

NB: STEP is the lossless and "industrial" format. I think GLTF is actually lossy.

**Comment by Peque** [comment]
Maybe relevant (about industry standards for 3D transmission formats):

- http://www.perey.com/ARStandards/3D_Transmission_Ninth_AR_Standards.pdf
- https://www.khronos.org/gltf/

**Comment by jmwright** [comment]
Cross-referencing issues: https://github.com/CadQuery/OCP/issues/8

**Comment by BrandonEscamilla** [comment]
HI, 

Is the GLTF exporter still in the plan?

**Comment by adam-urbanczyk** [comment]
Yes
