### ISSUE TITLE
Can CadQuery run in parallel (faster)?

### ISSUE THREAD

**Issue by OlegJakushkin** [CadQuery/cadquery#269]
So I installed `cadquery`  from `conda` like so:
```
conda install  -c conda-forge -c CadQuery CadQuery::pythonocc-core 
conda update  -c conda-forge  -c CadQuery -y --all
```

And I want to create a sphere. I try this sample:
```
import cadquery as cq
from cadquery  import exporters

wire = cq.Workplane("XY").threePointArc((1.0, 1.0), (0.0, 2.0)).close()
sphere = wire.revolve()
```

Yet it takes forever to finish... with `htop` showing 1 core 100% utilization

<img width="721" alt="Снимок экрана 2020-01-21 в 16 01 24" src="https://user-images.githubusercontent.com/2915361/72806964-614dad00-3c67-11ea-8d6a-adb00c06dd40.png">

What do I do wrong and are there any parallelization options in `cadquery`?

**Comment by jmwright** [comment]
There are not currently any parallelization options, and it's something I've looked into only briefly.

Your example completes almost instantly for me. I see that you have an exporter import at the top of the code snippet. If you're using an exporter and the precision is set too high, it can cause CPU utilization issues.

Please also compare your conda setup against the readme: https://github.com/CadQuery/cadquery#getting-started

**Comment by OlegJakushkin** [comment]
@jmwright  Thank you, `sphere.val().exportStl(file, precision=1e-3)`  solved infinit time issue=)
