### ISSUE TITLE
Local/global coordinate system problem

### ISSUE THREAD

**Issue by KAndrsn** [CadQuery/cadquery#280]
Example:  The goal is to create a curved handle and build a tool on the far end (because there is a hand grip on the near end).  I've simplified this to a simple rectangle cross-section.  I think part of my problem could be starting with plane "ZX", but I wanted to match my 3d printer's coordinate system and changing this causes things to break.

Attaching the extruded rect to the .faces() result.  The block is aligned to the global xyz, not the normal of the face. (Comment out the .workplane.transformed().)
![coord_problem face](https://user-images.githubusercontent.com/2774401/74594031-b7600700-4fff-11ea-9f77-1263d1da4638.PNG)

Attach the extruded rect to the .faces().workplane() result.  The extrude is along the normal to the face, but "up" gets reset/forgotten(?).
![coord_problem workplane](https://user-images.githubusercontent.com/2774401/74594075-2dfd0480-5000-11ea-8dcf-a6bff8a11102.PNG)

So, I added the .transformed() call to rotate 90 degrees about the local y-axis, but instead get this, which is rotated about the global Y axis.
![coord_problem transformed](https://user-images.githubusercontent.com/2774401/74594249-ec6d5900-5001-11ea-9070-9485c0c7cc90.PNG)

```import cadquery as cq
revolve_radius = 300
result = (cq.Workplane("ZX")
	.rect(10,20)
	.revolve(45.0, (1.0,revolve_radius), (-1.0,revolve_radius))
	)
result = (result
	.faces(">X and >Y")
	.workplane()
	.transformed(rotate=(0,90,0))
	)
result = (result
	.rect(10,20)
	.extrude(5)
	)
show_object(result)
```

**Comment by bragostin** [comment]
I think this issue is the same as #254
There is a Pull Request in the making to correct this behaviour I believe.
I found this workaround using ``toWorldCoords`` to work in my case:
```python
pln = part.faces(face).workplane(centerOption='ProjectedOrigin', origin=(0,0,0))
rot = cq.Vector(pln.plane.toWorldCoords((ANGLE, 0, 0))) 
part = pln.transformed(rotate=rot).pushPoints(xy).rect(Length, Width).cutBlind(Lcut)
```

**Comment by adam-urbanczyk** [comment]
This is what the code produces now. Is it the expected result @KAndrsn ?
![obraz](https://user-images.githubusercontent.com/13981538/87908566-e96e0d00-ca66-11ea-91c8-476408e47228.png)

**Comment by KAndrsn** [comment]
The goal is for the 10x20x5 block to align seamlessly with the end of the revolved extrusion.  The code above may be incorrect for this.  (Note: This is a simplified example.  The idea is to have a curved I-beam handle, and build the "tool" on the end of the handle. The 10x20x5 block would be a transition shape from the I-beam to... whatever.)

**Comment by adam-urbanczyk** [comment]
You can get it with the following code.
```python
revolve_radius = 300
result = (cq.Workplane("ZX")
	.rect(10,20)
	.revolve(45.0, (1.0,revolve_radius), (-1.0,revolve_radius))
	)
result = (result
	.faces(">X and >Y")
	.workplane()
	.transformed(rotate=(0,0,90))
	)
result = (result
	.rect(10,20)
	.extrude(5)
	)
show_object(result)
```
![obraz](https://user-images.githubusercontent.com/13981538/89318412-0f0e2f80-d67f-11ea-93fc-247e7eaa38b8.png)
