### ISSUE TITLE
Change Deprecated time.clock() Call in CQGI

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery#286]
A user reported this on the cadquery-freecad-module project, but it applies to CQ 2.0 as well.

https://github.com/jmwright/cadquery-freecad-module/issues/147

The gist of it is that `time.clock()` has been deprecated since Python 3.3, and was removed in Python 3.8. We need to switch the CQGI references over to either `time.perf_counter()` or `time.process_time()`.

Reference 1: https://github.com/CadQuery/cadquery/blob/102c16c14e42b6acca484efbf017f9ac2cc75789/cadquery/cqgi.py#L99

Reference 2: https://github.com/CadQuery/cadquery/blob/102c16c14e42b6acca484efbf017f9ac2cc75789/cadquery/cqgi.py#L124

**Comment by jwhevans** [comment]
Do you have a preference? time.perf_counter() is generally more accurate.

**Comment by jmwright** [comment]
I think `perf_counter` is fine. If I understand correctly, the main difference is it includes sleep time and interrupts, and `process_time` doesn't.

**Comment by jmwright** [comment]
Fixed in #305
