### ISSUE TITLE
 assembly of volumes

### ISSUE THREAD

**Issue by Shimwell** [CadQuery/cadquery#289]
Can't quite figure out how to make assemblies or parts with hierarchy.

I noticed the freecad based cadquery allowed this via cqparts but I'm not quite sure if this is possible in cadquery 2.0 or if there are plans to bring that functionality internally.

If it is possible is the there any chance we could have a minimal example please

**Comment by justbuchanan** [comment]
See the discussion at https://github.com/CadQuery/cadquery/issues/276.

**Comment by Shimwell** [comment]
Thanks for that link
