### ISSUE TITLE
Update OCP Branch

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery#299]
@adam-urbanczyk How hard would it be to bring the OCP branch up to date with master?

**Comment by adam-urbanczyk** [comment]
It shouldn't be too difficult. I'll take a look tomorrow-ish.

**Comment by jmwright** [comment]
Great, thanks.

**Comment by adam-urbanczyk** [comment]
Just did it, see #301 

All but one tests pass. The failing one is related to Face Sewing - some OCCT internals seem to have changed. We are not using this functionality in the fluent API currently.

**Comment by jmwright** [comment]
Thanks @adam-urbanczyk !
