### ISSUE TITLE
newObject and cut() method

### ISSUE THREAD

**Issue by bragostin** [CadQuery/cadquery#303]
I have created a newObject and want to perform a cut like this:
```python
cut_new = cq.Workplane('YZ').box(L,W,H)
new = cq.Workplane('XY').newObject(list_of_shapes)
cut_new = new.cut(shape_to_cut)
```
but nothing happens: the ``new`` object remains unchanged. Is that to be expected?

**Comment by adam-urbanczyk** [comment]
I don't think this is correct. Could you share a minimum reproducible example?

**Comment by bragostin** [comment]
@adam-urbanczyk 
This produces the intended result:
```python
import cadquery as cq
box1 = cq.Workplane('XY').box(10, 20, 30)
box2 = cq.Workplane('YZ').box(10, 20, 30)
shape_to_cut = cq.Workplane('XY').box(15, 15, 15).translate((8,8,8))
new_object = box1.union(box2)
cut_object = new_object.cut(shape_to_cut)
```
![unionObject_cut](https://user-images.githubusercontent.com/26216511/77521167-88e90d80-6e82-11ea-8775-06e5c93ffa83.png)
while this does not:
```python
import cadquery as cq
box1 = cq.Workplane('XY').box(10, 20, 30)
box2 = cq.Workplane('YZ').box(10, 20, 30)
shape_to_cut = cq.Workplane('XY').box(15, 15, 15).translate((8,8,8))
list_of_shapes = []
for o in box1.all(): list_of_shapes.extend(o.vals())
for o in box2.all(): list_of_shapes.extend(o.vals())
new_object = cq.Workplane('XY').newObject(list_of_shapes) 
cut_object = new_object.cut(shape_to_cut)
```
![newObject_cut](https://user-images.githubusercontent.com/26216511/77521243-a4541880-6e82-11ea-8f35-e69f8f9f15ba.png)
I would like to avoid using ``union`` because it is exceedingly slow with my real model.

**Comment by adam-urbanczyk** [comment]
Confirmed, it might be a kernel issue.

**Comment by adam-urbanczyk** [comment]
I made some progress: it seems that OCCT bool ops do not like if the original shape has self intersections. In your example the two boxes d intersect. For now the workaround would be to perform the cut before constructing the compound.

I will still try if using this method allows to pefrom such an op in a single shot
https://www.opencascade.com/doc/occt-6.9.1/refman/html/class_b_rep_algo_a_p_i___builder_algo.html#a46ae85feda209da3074b8b77af6670a7

**Comment by bragostin** [comment]
@adam-urbanczyk  then maybe a workaround could be to apply the the cut on each object of the list separately in a for loop?

**Comment by adam-urbanczyk** [comment]
Indeed, cut on separate objects and only then construct the compound.

**Comment by bragostin** [comment]
Indeed, the following code gives the expected result without unions:
```python
import cadquery as cq

box1 = cq.Workplane('XY').box(10, 20, 30)
box2 = cq.Workplane('YZ').box(10, 20, 30)
shape_to_cut = cq.Workplane('XY').box(15, 15, 15).translate((8,8,8))
list_of_shapes = []
for o in box1.all(): list_of_shapes.extend(o.vals())
for o in box2.all(): list_of_shapes.extend(o.vals())
list_of_shapes = [ cq.Workplane('XY').newObject([o]).cut(shape_to_cut) for o in list_of_shapes ]
list_of_shapes = [ o.val() for o in list_of_shapes ]
cut_object = cq.Workplane('XY').newObject(list_of_shapes)
```
