### ISSUE TITLE
How to access the solids inside a compound?

### ISSUE THREAD

**Issue by bragostin** [CadQuery/cadquery#309]
I do not manage to access the solids inside a compound individually. Is there a method that from a compound would yield a list of the solids inside the compound? I tried ``all()`` but it's not a Compound method.

**Comment by adam-urbanczyk** [comment]
Try `.Solids()` but AFAIR it will return all solids (i.e. also from nested Compounds). This might or might not be the desired behavior.

**Comment by bragostin** [comment]
@adam-urbanczyk Exactly what I need, thank you!
