### ISSUE TITLE
CQ + LR = love ? ...

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [CadQuery/cadquery#310]
I am curious if there is enough synergy / interest to join forces / reduce duplication:
https://github.com/LaughlinResearch/pyOCCT/issues/30

CQ:
https://github.com/CadQuery/pywrap
https://github.com/CadQuery/OCP

LR:
https://github.com/LaughlinResearch/pyOCCT
https://github.com/LaughlinResearch/pyOCCT_binder

**Comment by adam-urbanczyk** [comment]
The projects are indeed similar but have slightly different goals.
