### ISSUE TITLE
Possible bug in the Workplane method transformed(rotate=(0, 0, 0), offset=(0, 0, 0))

### ISSUE THREAD

**Issue by lalebarde** [CadQuery/cadquery#328]
This code:

```
import cadquery as cq
from jupyter_cadquery.cadquery import show
triangle = [[-1, 0], [1, 0], [0, 4]]
wp1 = cq.Workplane("XY").polyline(triangle).close().workplane()
wp2 = wp1.transformed(rotate=cq.Vector(30, 0, 0), offset=cq.Vector(0, 0, 0)).polyline(triangle).close().workplane()
result = wp2.loft(combine=True)
show(result)
```
results in:
![image](https://user-images.githubusercontent.com/3611049/79686318-c6ea0f00-823f-11ea-9fdf-ab7905a7d621.png)

There is an unexpected decay of 1 on the Y axis. If I take a triangle 100x bigger, the decay is 100.

Expected result looks like:

![image](https://user-images.githubusercontent.com/3611049/79686384-3eb83980-8240-11ea-897a-e9850c3cb875.png)

Artificially obtained with `offset=cq.Vector(0, -1.6, 0)`

**Comment by lalebarde** [comment]
With `rotate=cq.Vector(0, 0, 0), offset=cq.Vector(0, 0, 3)`, I have also the problem:

![image](https://user-images.githubusercontent.com/3611049/79686523-47f5d600-8241-11ea-802b-12f471ad4464.png)

**Comment by adam-urbanczyk** [comment]
First call to `workplane` changes the origin (you could use `centerOption='ProjectedOrigin'` or just skip `workplane()`). You probably want this:
```python
import cadquery as cq

triangle = [[-1, 0], [1, 0], [0, 4]]
wp1 = cq.Workplane("XY").polyline(triangle).close()
wp2 = wp1.transformed(rotate=cq.Vector(30, 0, 0), offset=cq.Vector(0, 0, 0)).polyline(triangle).close().workplane()
result = wp2.loft(combine=True)

show_object(result)
```

**Comment by lalebarde** [comment]
Thank you Adam, I should have known such a rough bug couldn't be
