### ISSUE TITLE
Surface Generation

### ISSUE THREAD

**Issue by akaszynski** [CadQuery/cadquery#330]
This is an awesome library!  I've gotten it working on jupyterlab and it's really great to be able to make CAD on the web.

#### Question:
I've seen no examples or documentation/methods to create a surface within `cadquery`.  Is there a way to do this without creating a solid model?

**Comment by jmwright** [comment]
@akaszynski Have a look [here](https://github.com/CadQuery/cadquery/blob/master/examples/Ex101_InterpPlate.py).

There's the related PR [here](https://github.com/CadQuery/cadquery/pull/253).

**Comment by akaszynski** [comment]
Thanks!  I'll try it out.

**Comment by jmwright** [comment]
@akaszynski Good luck. Let us know if you run into any issues.
