### ISSUE TITLE
User needs to create wires in the correct order

### ISSUE THREAD

**Issue by dcowden** [CadQuery/cadquery#34]
<a href="https://github.com/jmwright"><img src="https://avatars0.githubusercontent.com/u/1015439?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jmwright](https://github.com/jmwright)**
_Wednesday May 02, 2018 at 16:18 GMT_
_Originally opened as https://github.com/dcowden/cadquery/issues/260_

----

This was an [issue originally created](https://github.com/jmwright/cadquery-freecad-module/issues/113) by @Peque on the CadQuery FreeCAD module repo, but I think it's really an issue with the CadQuery API. This could potentially be fixed at the same time as #83 

Also see the discussion [here](https://github.com/jmwright/cadquery-freecad-module/issues/93)

**Comment by dcowden** [comment]
<a href="https://github.com/zwn"><img src="https://avatars3.githubusercontent.com/u/1130051?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zwn](https://github.com/zwn)**
_Monday May 14, 2018 at 05:54 GMT_

----

There is a solution suggested in https://github.com/jmwright/cadquery-freecad-module/issues/93#issuecomment-353746977. It involves in relying on `Freecad.Face()` to create the face from a list of wires.

**Comment by adam-urbanczyk** [comment]
This works correctly in CQ2.0:
![obraz](https://user-images.githubusercontent.com/13981538/59456880-99f6ef80-8e17-11e9-9a57-6c48ba8e7f8e.png)
CC: @Peque
