### ISSUE TITLE
"New" clears the code window without saving

### ISSUE THREAD

**Issue by maderero** [CadQuery/cadquery#341]
I ended up clearing a long stretch of code in the editor by hitting the "New" button instead of the "Save as" button. There were no options to undo the code or otherwise go back and no warnings of what was about to happen. I also could not find any temp files where the code may have been saved from the previous run. Is all of that code just gone for good, or am I missing something here?

**Comment by adam-urbanczyk** [comment]
I'm afraid it is lost (I'm assuming you are using CQ-editor). This issue was already reported here https://github.com/CadQuery/CQ-editor/issues/82 so I'm going to close this one.
