### ISSUE TITLE
Default cq.Workplane() to cq.Workplane("XY")

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#356]
That would be a reasonable default and would save some typing

**Comment by helmecke** [comment]
Done in https://github.com/CadQuery/cadquery/pull/380.

**Comment by adam-urbanczyk** [comment]
Indeed, thanks!

**Comment by michaelgale** [comment]
I give it two years before I remember to type `cq.Workplane()` instead of `cq.Workplane("XY")` :)
