### ISSUE TITLE
How to name a solid in order it appears in the CQ-Editor object view?

### ISSUE THREAD

**Issue by lalebarde** [CadQuery/cadquery#359]
Sorry if it has been already asked, I could not find an answer. Something as:

```
mysolid.set_name("some name")
print(mysolid.name)
```

![image](https://user-images.githubusercontent.com/3611049/82736575-251c7d00-9d2b-11ea-8fb4-61546992ca51.png)

[tag(name)](https://cadquery.readthedocs.io/en/latest/classreference.html#cadquery.CQ.tag) does not bring this. That would be nice to have.

**Comment by jmwright** [comment]
I can't remember for sure, but I think CQ-editor respects the label property, as did the FreeCAD workbench.

https://github.com/CadQuery/cadquery/blob/a140d1035c5ef058a5c89554ef7390873e10c370/cadquery/occ_impl/shapes.py#L234

**Comment by marcus7070** [comment]
> [tag(name)](https://cadquery.readthedocs.io/en/latest/classreference.html#cadquery.CQ.tag) does not bring this. That would be nice to have.

Unfortunately the method `tag` can not do that. It tags an "object", and by that I mean the Python definition of an object, not a CadQuery model. Almost every CQ operation actually returns a new object, and the tag is just a convenient way to search backwards through the chain of objects and find one in particular. You can read more about that here: https://cadquery.readthedocs.io/en/latest/primer.html#chaining

One method to display your models with a name showing is to actually not use `show_object`. When your script finishes without any calls to `show_object`, CQ-editor finds any `cadquery.Workplane` objects and displays them using the name you gave them in your script.
![screenshot2020-05-25-142014](https://user-images.githubusercontent.com/50230945/82779320-0afdae80-9e93-11ea-9c6e-233ec290621b.png)

**Comment by adam-urbanczyk** [comment]
Like so: `show_object(res,name='a')`.

**Comment by lalebarde** [comment]
Both your methods work, so either `self.label = ""` or `show_object(res,name='a')`

**Comment by lalebarde** [comment]
name does not work in FreeCAD which makes use of CQ v1
