### ISSUE TITLE
2d Spiral primative

### ISSUE THREAD

**Issue by dcowden** [CadQuery/cadquery#37]
<a href="https://github.com/fragmuffin"><img src="https://avatars0.githubusercontent.com/u/2626190?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fragmuffin](https://github.com/fragmuffin)**
_Tuesday Sep 19, 2017 at 11:04 GMT_
_Originally opened as https://github.com/dcowden/cadquery/issues/196_

----

In the interest of #195, we also need a method of making a spiral primative

something like:

```python
import cadquery
from Helpers import show
part = cadquery.Workplane("XY") \
    .spiral(radius=1, growth=2, radius=108).close() \
    .extrude(3)
show(part)
```

looking into https://freecadweb.org/wiki/Part_Spiral/en now

**Comment by dcowden** [comment]
<a href="https://github.com/fragmuffin"><img src="https://avatars0.githubusercontent.com/u/2626190?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fragmuffin](https://github.com/fragmuffin)**
_Wednesday Sep 20, 2017 at 12:59 GMT_

----

FreeCAD's spiral primitive implementation:
[`App::DocumentObjectExecReturn *Spiral::execute(void)`](https://github.com/FreeCAD/FreeCAD/blob/949c86d364f05eecb5e7c279d6b2bc20e76e65ec/src/Mod/Part/App/PrimitiveFeature.cpp#L907)

It makes a wire along a conical surface, then projects it onto a plane.
And there doesn't seem to be an existing python hook for it.

**Comment by adam-urbanczyk** [comment]
This is currently possible with parametric curves, cf. #110
