### ISSUE TITLE
Incorrect makeHelix output

### ISSUE THREAD

**Issue by nopria** [CadQuery/cadquery#385]
Method `makeHelix` gives incorrect result when the height, expressed in terms of  *number of turns*, is greater than a treshhold (42 in the following case):

```
import cadquery as cq

R = 50 # helix radius
N = 43 # helix turns - incorrect output for N > 42
P= 10 # helix pitch

show_object(cq.Wire.makeHelix(pitch=P, height=N*P, radius=R))
```

![incorrect-helix-opt](https://user-images.githubusercontent.com/4848618/85394750-54532380-b54f-11ea-9bdc-059e9b4078c7.png)

**Comment by marcus7070** [comment]
Very interesting!

If you drop the radius to 10, I can get 48.003 turns to work, 48.004 goes crazy.

**Comment by adam-urbanczyk** [comment]
Good catch @nopria ! I seems that you found some limitations of the `BRepLib.BuildCurves3d_s` call in `makeHelix`. If I use different settings `BRepLib.BuildCurves3d_s(w,1e-9,MaxSegment=1000)` it works. But there will be always an upper bound what this call can handle.
