### ISSUE TITLE
Cannot choose which rotated plane to select

### ISSUE THREAD

**Issue by bragostin** [CadQuery/cadquery#447]
The code below is aimed at boring a hole through a double rotated cylinder from its outmost face to created a pipe:
```python
import cadquery as cq
import numpy as np
from scipy.spatial.transform import Rotation as R

L = 65.
W = 123.
EH = 6.
WT = 1.
FRO = 2.
FRI = 2.
PDL = 40
PDO = 6.35
PDI = 4

EV = cq.Workplane('XY').box(EH+2*WT, W, L).edges().chamfer(FRO)
EV_cutin = cq.Workplane('XY').box(EH, W-2*WT, L-2*WT).edges().chamfer(FRI)
EV = EV.cut(EV_cutin)

AP = (13,13,0)
EV = EV.faces('<Z').workplane(offset=-FRO).center(0, 40).transformed(AP).circle(PDO/2).extrude(PDL)

v = np.array([0, 0, -1])
r = R.from_euler('xyz', list(AP), degrees=True)
v = r.apply(v)
sel = '+' + str(tuple(v))

EV = EV.faces(sel).workplane().hole(PDI, PDL+FRO)

show_object(EV)
```
however it select the inmost face and bore the hole in the wrong direction as shown below. I cannot select the other face, apparently ``[1]`` selector does not work with arbitrarily oriented planes. Is there any obvious workaround?
![select_rotated_plane](https://user-images.githubusercontent.com/26216511/92321237-b5f03d80-f028-11ea-862f-094ad580b360.png)

**Comment by adam-urbanczyk** [comment]
You probably want:
```python
sel = '>' + str(tuple(v))
```

**Comment by bragostin** [comment]
@adam-urbanczyk this is interesting, when first tried ``sel = '>' + str(tuple(v))`` in my main script I got this:
<img width="719" alt="select_rotated_plane" src="https://user-images.githubusercontent.com/26216511/92324777-007fb300-f045-11ea-9fd0-d4400ed3f48d.png">
that's why I used ``sel = '+' + str(tuple(v))``. But in the simplified script I showed above ``sel = '>' + str(tuple(v))`` yields the expected result:
![select_rotated_plane](https://user-images.githubusercontent.com/26216511/92324813-5bb1a580-f045-11ea-99a4-53d3171255d6.png)

So I guess something is wrong in my main script.

**Comment by bragostin** [comment]
Update: if I add ``v = np.round(v, 1)`` which results in ``sel =  >(-0.2, 0.2, -0.9)`` instead of ``sel =  >(-0.2191855733945387, 0.22495105434386498, -0.9493970231495834)`` then I get the correct result in my main script too. There seem to be some rounding issue that makes CadQuery select the wrong plane.

**Comment by adam-urbanczyk** [comment]
Can you post a reproducible example ? Note that there is no implicit rounding in CQ, so it sounds like your main script has some issue. Once selected, you can verify that orientation of your face using e.g. `val().normalAt()`

**Comment by bragostin** [comment]
Yes, now if you set ``PDL = 26.`` in the code above, the issue should appear as below. Note that the issue disappears when PDL>=26. Might that be a kernel issue?
![select_rotated_plane](https://user-images.githubusercontent.com/26216511/92325929-9966fc00-f04e-11ea-8d46-67d6c7bb234b.png)

**Comment by bragostin** [comment]
Possibly a clue: the wrong plane is selected when the condition ``sel = >(-0.2191855733945387, 0.22495105434386498, -0.9493970231495834)`` is met by another face. But I thought the exact face orientation should be respected.
![select_rotated_plane](https://user-images.githubusercontent.com/26216511/92327378-8c9bd580-f059-11ea-9448-77dbaf08e60f.png)

**Comment by adam-urbanczyk** [comment]
`>` and `<` do not filter on orientation they just order objects according to the projection of their center on the given axis. For the model above you can actually use
```python
.faces('<Z')
```
I checked the orientation of the face and the following selector works for me:
```python
sel = "+(0.22495105434386492,0.21918557339453917,-0.9493970231495835)"
```
Note that it is different than what you have in v:
```python
v
Out[28]: array([-0.21918557,  0.22495105, -0.94939702])
```
BTW: you don't need to construct workplane orientations by hand - you can always use the `.plane.zDir` property.

**Comment by bragostin** [comment]
@adam-urbanczyk thank you, this helped me to sort this issue out finally!
``.faces('<Z')`` works indeed, but only if there are other faces further away. If I add a second straight longer cylinder, it selects the longer one.
But then, using the selector you identified, the following code works even with the longer cylinder:
```python
import cadquery as cq
import numpy as np
from scipy.spatial.transform import Rotation as R


L = 65.
W = 123.
EH = 6.
WT = 1.
PDL = 26.
PDO = 6.35
PDI = 4
DW = 40.

FRO = 2.
FRI = 2.

EV = cq.Workplane('XY').center(-0.5,0).box(EH+2*WT, W, L).edges().chamfer(FRO)
EV_cutin = cq.Workplane('XY').box(EH, W-2*WT, L-2*WT).edges().chamfer(FRI)
EV = EV.cut(EV_cutin)

AP = (13,13,0)
EV = EV.faces('<Z').workplane(offset=-FRO).center(0, DW).transformed(AP).circle(PDO/2).extrude(PDL)
EV = EV.faces('<Z[-1]').workplane(offset=-FRO).center(0, -DW).circle(PDO/2).extrude(1.5*PDL)

AP = (-13, -13, 90)
v = np.array([0, 0, -1])
r = R.from_euler('xyz', list(AP), degrees=True)
v = r.apply(v)
sel = '+' + str(tuple(v))

EV = EV.faces(sel).workplane().hole(PDI, PDL+FRO)

show_object(EV)
```
![select_rotated_plane](https://user-images.githubusercontent.com/26216511/92372219-e99c9780-f0fc-11ea-99e9-59d7787f1a3d.png)

I don't really understand the reason for having to use a different rotation ``AP = (-13, -13, 90)`` for the selector vector to obtain the one you identified though, but it works, thanks a lot!
