### ISSUE TITLE
Projects using CadQuery - Outdated/broken links

### ISSUE THREAD

**Issue by frafra** [CadQuery/cadquery#450]
Hi,
Almost every single link under "Projects using CadQuery" is broken, while one points to a repository which requires CadQuery 1.x. Should this section be cleaned up or updated?

**Comment by jmwright** [comment]
@frafra Yeah, probably. The KiCAD project won't work with CadQuery 2.0, but most other CQ 1.x scripts will with a little tweaking. The links will have to be updated and the KiCAD project removed.

**Comment by jmwright** [comment]
Addressed in #462
