### ISSUE TITLE
text() fontsize parameter dimensions unclear

### ISSUE THREAD

**Issue by nirvdrum** [CadQuery/cadquery#463]
The documentation for the `fontsize` parameter of the `text` function says "size of the font" but it's unclear how that size is defined. While the value is dimensionless, what does it refer to? The size of a particular character? Something else? I'm happy to open up a PR to improve the documentation. but I'd need a little clarification before doing so.

**Comment by jmwright** [comment]
Looks like the font size might be in model units. https://old.opencascade.com/doc/occt-7.4.0/refman/html/class_font___b_rep_font.html#ae3b9cc7e8a840f817a0c15edd18e14e7

**Comment by adam-urbanczyk** [comment]
I assume it is the maximum height of a letter + some margin. Here is a capital letter of size 1 on top of a 1x1 face:
![obraz](https://user-images.githubusercontent.com/13981538/95677896-2c083700-0bc9-11eb-87d0-4bcb4b5b8d91.png). 
I guess that the font size  (disregarding units) has the same meaning as in any other application (never checked this assumption though). BTW: FreeType is used for handling fonts on the CAD kernel side.
