### ISSUE TITLE
extrude by rotating around axis ?

### ISSUE THREAD

**Issue by MarcWeber** [CadQuery/cadquery#495]
It's not in the planned features and I failed finding it ine the api.
PyMSH seems to implement it based on OCC: https://bthierry.pages.math.cnrs.fr/tutorial/gmsh/occ_spline/
I failed finding the OCC primitives, but probably I just don't know it well enough.

Can you add it to the examples/documentation or planned features ?

If OCC supports it can you point me to the name I missed to look it up ?

**Comment by marcus7070** [comment]
Is `Workplane.revolve` what you are looking for?

https://cadquery.readthedocs.io/en/latest/classreference.html#cadquery.Workplane.revolve

**Comment by jmwright** [comment]
Here's an example as well. https://github.com/CadQuery/cadquery/blob/master/examples/Ex022_Revolution.py

**Comment by MarcWeber** [comment]
Yes, revolve is exactly what I was looking for. I missed it cause I only searched for extrude and alike.

https://cadquery.readthedocs.io/en/latest/apireference.html

Maybe the documentation text >>Use all un-revolved wires in the parent chain to create a solid.<< could be improved a little. But maybe this github issues is also enough to be found by people like me :-/

CadQuery is cool.
