### ISSUE TITLE
Workplane.sweep documentation cleanup

### ISSUE THREAD

**Issue by trayracing** [CadQuery/cadquery#498]
Workplane.sweep documentation could use a bit of tweaking:

1. The implication of multisection is not described.
2. Unclear why sweepAlongWires is optional[bool] instead of bool.
3. Only 5 of 8 parameters have descriptions in cq.py.
4. The generated documentation repeats some parameters in a mangled fashion at 
[](https://cadquery.readthedocs.io/en/latest/classreference.html?highlight=sweep#cadquery.Workplane.sweep) For example, `clean` occurs twice, once with explanation

**Comment by adam-urbanczyk** [comment]
The docstrings are there - it is an issue of docs generation.
