### ISSUE TITLE
Sensitive Data Exposure

### ISSUE THREAD

**Issue by TharunRajj** [CadQuery/cadquery#510]
How to reproduce a Bug: 1)Go to https://github.com/ryaghmaie1/CAD-Query/blob/453d2cdfb76615bb7b1478394eea10245b74e3f8/appveyor.yml 2)A anaconda token can be exposed. So it is a critical issue.
![Capture code](https://user-images.githubusercontent.com/49275307/99351506-b7f73800-28c6-11eb-9a03-e03bfb5c02f6.PNG)

**Comment by adam-urbanczyk** [comment]
Thanks for reporting, but how did you conclude that this is an unencrypted token? Last time I checked the `secure` section contained encrypted variables. Did you use this token successfully to access anaconda?

**Comment by TharunRajj** [comment]
Nope. I just report it to you. Because anyone can use this token for harmful purposes.

**Comment by adam-urbanczyk** [comment]
According to me it is an encrypted token. You cannot just use it, you have to first decrypt it. Are you saying that the encryption is somehow compromised or what precisely is wrong here?
