### ISSUE TITLE
some volume checks are too strict

### ISSUE THREAD

**Issue by greyltc** [CadQuery/cadquery#513]
Not really sure why (maybe because I'm on OCCT 7.5?), but I'm barely failing some of the volume checks so I relaxed them a bit:
https://github.com/greyltc/cadquery/commit/a0ecf8ec23003859654087ba16343621aaecb8f3
https://github.com/greyltc/cadquery/commit/3fdf585e640bbee0e41cfd1c3ba817e28e132937

**Comment by adam-urbanczyk** [comment]
See #512, CQ works on 7.4 for now.
