### ISSUE TITLE
Combine() has no glue=True option

### ISSUE THREAD

**Issue by bragostin** [CadQuery/cadquery#533]
`combine(self, clean: bool = True)` does not have the glue=True option, which was recently implemented in `union()` and is very useful.
Would you accept that I do a pull request to implement it?

**Comment by jmwright** [comment]
+1 from me, but I would wait to see what @adam-urbanczyk says as well.

**Comment by adam-urbanczyk** [comment]
+1

**Comment by adam-urbanczyk** [comment]
Solved by #535
