### ISSUE TITLE
exporting a wire to stl

### ISSUE THREAD

**Issue by Shimwell** [CadQuery/cadquery#537]
I noticed a potential bug and thought it was worth reporting.

When I make a 3D solid I can export it as a stp file and stl file, it all works fine

```python
import cadquery as cq
from cadquery import exporters

result_solid = cq.Workplane("front").lineTo(2.0, 0).lineTo(2.0, 1.0).threePointArc((1.0, 1.5),(0.0, 1.0))\
    .close().extrude(0.25)

with open('result_solid.stl', "w") as out_file:
    exporters.exportShape(result_solid, "STL", out_file)

with open('result_solid.stp', "w") as out_file:
    exporters.exportShape(result_solid, "STEP", out_file)
```
stp and stl file
![Screenshot from 2020-12-09 13-45-24](https://user-images.githubusercontent.com/8583900/101637823-29895880-3a25-11eb-843a-a5d9333f72c8.png)
![Screenshot from 2020-12-09 13-45-02](https://user-images.githubusercontent.com/8583900/101637825-2a21ef00-3a25-11eb-9d1b-259f33405aae.png)

However when I make a 2D wire (same as 3D but with no extrude) then the stp export works but the stl export results in a 0 byte file (hence no screen shot for that one).

```python
result_line = cq.Workplane("front").lineTo(2.0, 0).lineTo(2.0, 1.0).threePointArc((1.0, 1.5),(0.0, 1.0))\
    .close()
# note the lack of extrude here

with open('result_line.stl', "w") as out_file:
    exporters.exportShape(result_line, "STL", out_file)

with open('result_line.stp', "w") as out_file:
    exporters.exportShape(result_line, "STEP", out_file)
```
stp file
![Screenshot from 2020-12-09 13-44-53](https://user-images.githubusercontent.com/8583900/101637875-3b6afb80-3a25-11eb-926b-68da6e11d079.png)

stl file is zero bytes and has no contents

I'm using the CQ master branch, Ubuntu 18.04 and python 3.8

Would be interested to know if this is a bug or I have perhaps done something wrong

**Comment by adam-urbanczyk** [comment]
I think that STL can only represent triangles, it should be possible to export the face though.

**Comment by Shimwell** [comment]
Ah yes that makes sense. Thanks
