### ISSUE TITLE
Time for 2.1 RC

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#539]
I propose to merge #535,  #537 and then tag 2.1RC

**Comment by adam-urbanczyk** [comment]
OK, so in principle it is time for 2.1RC . What do you think about #549 ?

**Comment by jmwright** [comment]
I think since it's an RC merging #549 first is fine.

**Comment by adam-urbanczyk** [comment]
I was actually thinking about waiting with it. There might be still some work needed for #549 and it would be nice to at least have the RC1 before the FOSDEM deadline - I think I'll submit something after all.

**Comment by adam-urbanczyk** [comment]
If you agree just tag it today.

**Comment by jmwright** [comment]
> I was actually thinking about waiting with it.
> There might be still some work needed for #549 and it would be nice to at least have the RC1 before the FOSDEM deadline.
> If you agree just tag it today.

I'm not sure what you mean. As I read those three lines, the first makes me think you want to wait to do the release, but the second two seem like you want to go ahead and do it. I'm ok with either.

**Comment by adam-urbanczyk** [comment]
LOL. I meant:  I was actually thinking about waiting with #549 .

**Comment by jmwright** [comment]
Ok, that sounds good. Feel free to create a tag, or I'll find some time later today to do it.

**Comment by jmwright** [comment]
Ok, the RC release has been tagged. https://github.com/CadQuery/cadquery/releases/tag/2.1RC1

**Comment by marcus7070** [comment]
@jmwright, did you want to update changes.md?

**Comment by jmwright** [comment]
> did you want to update changes.md?

Yes, that's a good point. I'll make sure it's done before the full release.

**Comment by jmwright** [comment]
Changelog updates are in #557

**Comment by jmwright** [comment]
I think we've completed this task, so I'm going to close.
