### ISSUE TITLE
DOC: pypi long_description is broken

### ISSUE THREAD

**Issue by dcowden** [CadQuery/cadquery#54]
<a href="https://github.com/westurner"><img src="https://avatars2.githubusercontent.com/u/50891?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [westurner](https://github.com/westurner)**
_Thursday Jul 19, 2018 at 20:39 GMT_
_Originally opened as https://github.com/dcowden/cadquery/issues/287_

----

https://pypi.org/project/cadquery/

https://github.com/pypa/readme_renderer#check-description-locally

**Comment by jmwright** [comment]
Closing since this is a CadQuery 1.x issue. I'm now attempting to generate a new bug fix tag of CadQuery 1.x so that things like PyPi will be updated with the information that CQ 1.x is not to be used for new projects.
