### ISSUE TITLE
Reproducing examples

### ISSUE THREAD

**Issue by anujdeshpande** [CadQuery/cadquery#542]
Hi

I am trying to reproduce the example of a parametric box - https://pythonhosted.org/cadquery/examples.html#a-parametric-enclosure - locally in CQ editor

I wasn't able to do so - see the image below
I only added `import cadquery as cq` to the first line, and `show_object(result)` to the last line

What am I missing? 
![image](https://user-images.githubusercontent.com/969376/101978525-9007b400-3c7b-11eb-8f7d-f189f1c74be5.png)

**Comment by adam-urbanczyk** [comment]
Could you try the latest docs: https://cadquery.readthedocs.io/en/latest/examples.html ?

**Comment by anujdeshpande** [comment]
This worked! Thanks!
