### ISSUE TITLE
construction error with 360 degree circle

### ISSUE THREAD

**Issue by Shimwell** [CadQuery/cadquery#544]
I was just trying to union a couple of shapes and got it working when the shapes are revolved by 180 but appear to get an error when revolving to 360 degrees.

I've made a minimal example here

```python
import cadquery as cq
from cadquery import exporters

angle = 360 # 360 causes error by 180 works

triangle = (
    cq.Workplane("XY")
    .polyline([
        (4235.0, 4170.0),
        (2862.237128095924, 2191.6819397473832),
        (3200.5113335386786, 1995.5912415180355),
    ])
    .close()
    .revolve(angle)
)

circle = (
    cq.Workplane("front")
    .moveTo(3700., 3100.)
    .circle(250)
    .revolve(angle)
)

both = circle.union(triangle)

with open('both.stp', "w") as f:
    exporters.exportShape(both, "STEP", f)
```

There error that occurs appears to be caused by the union of the two shapes when they are 360 revolves. The union works for a 180 degree rotation.

![Screenshot from 2020-12-13 01-16-52](https://user-images.githubusercontent.com/8583900/102000606-fb37a180-3ce0-11eb-98e5-1ae6c2a5f8c2.png)

This is the shape when using ```angle=180``` exported to a stp file using CadQuery 2 (master version). I just used FreeCAD for the loading of the step file. The python code was run with the latest CQ master version.

![Screenshot from 2020-12-13 01-19-26](https://user-images.githubusercontent.com/8583900/102000622-45208780-3ce1-11eb-8ce7-045019ee7ca9.png)

**Comment by jmwright** [comment]
@Shimwell If you use a revolution angle of 359 or 359.9, does it still work like the 180 degree revolve? We've seen that problem before in a somewhat different context.

**Comment by adam-urbanczyk** [comment]
It's not a revolve issue - it is related to the final union. Traditionally `clean=False` does the job
```python
angle = 360 # 360 causes error by 180 works

triangle = (
    cq.Workplane("XY")
    .polyline([
        (4235.0, 4170.0),
        (2862.237128095924, 2191.6819397473832),
        (3200.5113335386786, 1995.5912415180355),
    ])
    .close()
    .revolve(angle)
)

circle = (
    cq.Workplane("front")
    .moveTo(3700., 3100.)
    .circle(250)
    .revolve(angle)
)

both = circle.union(triangle, clean=False)
```

**Comment by Shimwell** [comment]
Thanks for the solutions.

I can confirm that the setting the revolved to 359 and 359.9 the shape with the union worked over here.

Also the clean = False arg in the union allowed 360 revolutions which is just perfect for my use case.

Many thanks

**Comment by adam-urbanczyk** [comment]
What do you mean, I can get the following result that looks IMO fine (section added for clarity):
![image](https://user-images.githubusercontent.com/13981538/102012779-9d40a380-3d4c-11eb-821b-96cc3f4347a1.png)
```python
both = circle.union(triangle, clean=False).shell(-50)
bot_sh = both.section()
```

**Comment by Shimwell** [comment]
ah it is working again now, I'm sure it was causing difficulty. Let me figure this out a bit more I think there is one more thing to solve but my script involves so many stages I need to narrow it done a bit more.

**Comment by Shimwell** [comment]
![Screenshot from 2020-12-13 17-51-34](https://user-images.githubusercontent.com/8583900/102019545-0c79c000-3d6c-11eb-8f79-9d50f8ea6c28.png)

**Comment by Shimwell** [comment]
Everything is working and the clean=False is happily working with the shell. I was trying to shell a shape that wasn't completed revolved and the spline edges were not working that well. But revolving it 360 degrees so that there were less faces made it easier to shell.
