### ISSUE TITLE
object_show does not work

### ISSUE THREAD

**Issue by dcowden** [CadQuery/cadquery#55]
<a href="https://github.com/totyped"><img src="https://avatars0.githubusercontent.com/u/32427425?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [totyped](https://github.com/totyped)**
_Monday Aug 13, 2018 at 11:24 GMT_
_Originally opened as https://github.com/dcowden/cadquery/issues/290_

----

On Ubuntu, jupyter-notebook, python 2

When I type

```
import cadquery as cq
result = cq.Workplane("front").box(2.0, 2.0, 0.5)
show_object(result)
```
I get the following error:
NameError                                 Traceback (most recent call last)
<ipython-input-6-4fa5d0e1a19a> in <module>()
      1 result = cq.Workplane("front").box(2.0, 2.0, 0.5)
----> 2 show_object(result)

NameError: name 'show_object' is not defined

**Comment by adam-urbanczyk** [comment]
Am I missing something here? `show_object` is not imported anywhere so why should it be defined magically in jupyter?

**Comment by jmwright** [comment]
show_object is handled by CQGI during script execution, and is never explicitly imported. I know @RustyVermeer had it working in Jupyter Notebook at one time with CQNB. @dcowden was talking about changing show_object to be explicitly imported at one point as well. I don't know where all that stands now.

**Comment by dcowden** [comment]
@adam-urbanczyk  true! 

The goal of CQGI is to provide an interface so that stand alone scripts can also be run in varous UIs ( juptyer, or cadquery-freecad-module ), without needing changes.

The essence of this approach is to make sure that not matter what environment you'r running in, show_object is defined. 

There was a long discussion here https://github.com/cqparts/cqparts/issues/66
which led to this issue: https://github.com/CadQuery/cadquery/issues/29

In the end, we agreed that the cadquery cqgi package needs to export functions for showing and debugging objects, and then underlying execution platforms ( jupyter, cadquery freecad module, command line runners, etc), should integrate behind cqgi so that the scripts are portable.

**Comment by jmwright** [comment]
I had asked the original poster if they are using CQNB and they never responded, and Rusty never responded. Maybe it's best to close this and let them re-open if they're interested in continuing the conversation.

**Comment by adam-urbanczyk** [comment]
My point is, that a (plain) jupyter python notebook is (for the sake of this argument) not much more than a python interpreter. Without explicitly importing a function it will not be available (unless we start using some weird tricks like modifying `__builtins__`, but that wouldn't be a good idea).

Other thing is that we do not have jupyter notebook support in core CQ yet.

**Comment by dcowden** [comment]
@adam-urbanczyk i'm not sure if im understanding completely, but i agree with you. I feel like we ultimately agreed that scripts shoudl have to directly import something to show objects, so there is no magic. like

`from cqgi import show_object`

or, others had proposed decorator functions that are more flexible to support cqparts, but none the less an import, like

```from cqgi import part
...

@cqgi.part
def myfunction_that_returns_a_part():
```

IE, i think everyone was agreed that we should NOT continue modifying built-ins or other magic like cqgi does now, where a show_object method appears out of nowhere.

**Comment by jmwright** [comment]
I feel like CQNB and the newer Enhanced Jupyter Extension address this issue.

https://groups.google.com/forum/m/#!topic/cadquery/Gw4yv1rZoE4

Making the show_object import explicit is a separate issue that I'll break out.
