### ISSUE TITLE
String selectors do not support "%Ellipse"

### ISSUE THREAD

**Issue by bernhard-42** [CadQuery/cadquery#559]
Maybe https://github.com/CadQuery/cadquery/blob/a3ebdb961d146464035621c407a22a8e3261cd6d/cadquery/selectors.py#L531 should be extended with the string `"Ellipse"`?
I made a quick test by patching my underlying cadquery in site-packages and it seems to work.

**Comment by adam-urbanczyk** [comment]
Fixed in #549 for all geometry types defined in cq.
