### ISSUE TITLE
CQ is going to FOSDEM2021

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#566]
Location/devroom: [open source computer aided modeling and design](https://fosdem.org/2021/schedule/track/open_source_computer_aided_modeling_and_design)

If you have some nice models/screenshots to share please do so here!

**Comment by jmwright** [comment]
I think I've previously mentioned a side project of mine involving a tensegrity structure. There is still a bug in the string placement code so a couple of those are out of place, but I can have it fixed pretty quickly to give a better screenshot if you're interested in using it. If you don't want to use it, no problem.

It's based on the mathematics laid out in a research paper, and I implemented it (with a few shortcuts) in CadQuery via Numpy, and then used CQ's newer assembly functionality to put everything together. In theory, I can change the major and minor radii of the torus and have everything adjust appropriately.

Blue = bar
Red = String
![Screenshot from 2021-01-06 17-38-26](https://user-images.githubusercontent.com/1015439/103827170-593c7800-5046-11eb-902d-31bc3bc09c29.png)

**Comment by michaelgale** [comment]
As always, feel free to use any media here:  https://github.com/fx-bricks/fx-cad-notes

Also, you can find a high quality render(with Blender from STL exported from CQ) of one of our newest CQ built products here:
https://www.flickr.com/photos/michaelgale/50024337707/in/dateposted-public/

and the real thing soon to be released on the market here:
https://www.flickr.com/photos/michaelgale/50674016407/in/dateposted-public/

**Comment by adam-urbanczyk** [comment]
Both examples look great to me, thanks!

**Comment by bragostin** [comment]
How about this one? The Tetrakaidecahedron (Kelvin Cell) can pave 3D space and is often encountered in cristallography.
![FODSEM_Tetrakaidecahedron_iso](https://user-images.githubusercontent.com/26216511/103934143-ca525d00-5124-11eb-8aa9-e2e932587004.png)

**Comment by jmwright** [comment]
@bragostin Very cool. Do you have a link to some code?

@adam-urbanczyk I think the router spindle assembly would be a good one too.

**Comment by bragostin** [comment]
@jmwright  yes, there https://github.com/bragostin/CadQuery-Examples/blob/main/Tetrakaidecahedron.py
It can surely be improved.

**Comment by jmwright** [comment]
@adam-urbanczyk If you decide to include it, tensegrity structure image is [here](https://github.com/jmwright/IslandOne/blob/master/docs/static/images/i1_full_tensegrity_structure_with_ground_deck.png) and the readme with background info is [here](https://github.com/jmwright/IslandOne/blob/master/README.md).

**Comment by adam-urbanczyk** [comment]
Thanks everyone, the video is online:
https://video.fosdem.org/2021/D.cad/cadquery.webm
