### ISSUE TITLE
Same options for centered in methods .rect and .box

### ISSUE THREAD

**Issue by marcus7070** [CadQuery/cadquery#567]
I think we can change the way we specify `centered` in both `.rect` and `.box` to be more consistent and more useful. Basically: 
* Keep existing behaviour for `.rect(1, 1, centered=True)` and `.box(1, 1, 1, centered=(True, True, True)`
* `.rect(10, 10, centered=(True, False)` produces a rectangle with corners on (-5, 0) and (5, 10)
* `.box(1, 1, 1, centered=True` is the same as `.box(1, 1, 1, centered=(True, True, True)`

Thoughts?

**Comment by marcus7070** [comment]
These methods also use a 2 or 3d centered option, and could be given the same treatment:

* `rarray`
* `sphere`
* `wedge`

**Comment by RubenRubens** [comment]
I think it's a good idea. Making stuff more consistent is always welcome.

**Comment by michaelgale** [comment]
I like this suggestion.  I can't count how many times I adjust objects by `(-xyz/2)`!  As long as the default behaviour isn't broken, this would be useful.

**Comment by adam-urbanczyk** [comment]
Sounds good, do you mind waiting till after 2.1?

**Comment by marcus7070** [comment]
> Sounds good, do you mind waiting till after 2.1?

No worries, that is fine.
