### ISSUE TITLE
FreeCAD reference on docs

### ISSUE THREAD

**Issue by RubenRubens** [CadQuery/cadquery#575]
Read the docs :open_book::
https://github.com/CadQuery/cadquery/blob/ccf56e6455b74e09e2709dfc4914ee33a51ec3ea/cadquery/cq.py#L404-L412

I have no idea what this one does. There are other 13 references in `cadquery/cq.py` about FreeCAD.

**Comment by jmwright** [comment]
The doc string was apparently never updated from when CQ was built on top of FreeCAD. In CQ 2.0 it returns the underlying OCCT object.

**Comment by jmwright** [comment]
I guess more accurately, that method used to be called `toFreecad()` and the doc string never got updated.

**Comment by adam-urbanczyk** [comment]
I'll amend it in #573

**Comment by adam-urbanczyk** [comment]
Solved in #573.
