### ISSUE TITLE
Cannot draw array on a 2-dimensional plane

### ISSUE THREAD

**Issue by brianng0305** [CadQuery/cadquery#576]
I have no problem with using below code on 3d array(add .extrude). But only 1 circle appears when I would like to draw a 10*2 array on a 2-dimensional plane. What is the problem?

`import cadquery as cq

result = cq.Workplane("XY").rarray(100,100,10,2).circle(10)

show_object(result)`
Thank you for your help.

![Screenshot from 2021-01-13 11-11-25](https://user-images.githubusercontent.com/36631693/104402023-5551ae00-5590-11eb-997f-6ca500b1f531.png)

**Comment by jmwright** [comment]
@brianng0305 Unless you have a compelling reason to run the FreeCAD workbench, I would suggest switching to CQ-editor. The FreeCAD workbench does not support CadQuery 2.x. There are still old tutorial videos pointing to FreeCAD, but it is non-trivial to make it compatible with CadQuery 2.x. CQ-editor repo: https://github.com/CadQuery/CQ-editor

Your code works fine for me in CQ-editor.
![Screenshot from 2021-01-13 06-51-53](https://user-images.githubusercontent.com/1015439/104448981-e7938b00-556b-11eb-9d7a-866e5569ab7f.png)

**Comment by adam-urbanczyk** [comment]
I can also confirm that it works on the latest CQ/CQ-editor.

**Comment by brianng0305** [comment]
Thank you jmwright and Adam. It works under CQ-editor.

I didn't use CQ editor since it crushed to the existing conda-environment. It works with the new conda-environment.

Thanks!!
