### ISSUE TITLE
Time for 2.1 release?

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#578]
I think after merging #573 we are good to go

**Comment by adam-urbanczyk** [comment]
Will investigate #355 before this - could be a low-hanging fruit.

**Comment by skanga** [comment]
Will you be providing a windows binary (exe file) in this release?

**Comment by adam-urbanczyk** [comment]
I think we are good to go - just need to edit `changes.md`. What do you think @jmwright ?

**Comment by jmwright** [comment]
@adam-urbanczyk I think that's fine. Do you want to merge #614 before the 2.1 release? If you want me to draft a release I can do it tomorrow (Wednesday) and can update changes.md.

**Comment by adam-urbanczyk** [comment]
Thanks, that would be great. I already merged #614 .

**Comment by jmwright** [comment]
2.1 release is [here](https://github.com/CadQuery/cadquery/releases/tag/2.1)
