### ISSUE TITLE
Array an object

### ISSUE THREAD

**Issue by brianng0305** [CadQuery/cadquery#586]
Good morning.

I would like to make an array of L shape

so I type:
`L = cq.Workplane("XY").circle(10).extrude(-500)
L = L.transformed(offset=cq.Vector(0,0,-500)).transformed(rotate=cq.Vector(90,0,0))\
.circle(12).extrude(-500)` 

and then
`Ls = cq.Workplane("XY").rarray(100, 100, 10, 1, center=True).L`

Cq-editor said workplane has no attribute L.

So i type:
`Ls = cq.Workplane("XY").rarray(100, 100, 10, 1, center=True).circle(12).extrude(-500).transformed(offset=cq.Vector(0,0,-500)).transformed(rotate=cq.Vector(90,0,0)).rarray(100, 100, 10, 1, center=True).circle(12).extrude(-500)
`
It works.

![L](https://user-images.githubusercontent.com/36631693/104830066-bb527400-58b5-11eb-9bc2-c1aaa93aa5ba.jpg)

I tried to use for loop to simplfy the procedure of array. Cq-editor said int can not be iterable. I failed.:

`n = 5
for x in 20:
    if x % n == 0:
L = cq.Workplane("XY").transformed(offset=cq.Vector(x,0,0).circle(10).extrude(-500)
L = L.transformed(offset=cq.Vector(0,0,-500)).transformed(rotate=cq.Vector(90,0,0))\
.circle(12).extrude(-500)
`
Can I simplfy the procedure of array objects?

Thank you.

**Comment by jmwright** [comment]
You could maybe use CadQuery's plugin system. https://cadquery.readthedocs.io/en/latest/extending.html#extending-cadquery-plugins
```python
import cadquery as cq

def createLs(self):
    L = cq.Workplane().circle(10).extrude(-500)
    L = L.transformed(offset=cq.Vector(0,0,-500)).transformed(rotate=cq.Vector(90,0,0)).circle(12).extrude(-500)

    return self.eachpoint(lambda loc: L.val().located(loc), True)

cq.Workplane.createLs = createLs

L2 = cq.Workplane("XY").pushPoints([(0, 0), (100, 0), (200, 0)]).createLs()

show_object(L2)
```
![Screenshot from 2021-01-17 15-03-56](https://user-images.githubusercontent.com/1015439/104854549-42631480-58d5-11eb-817b-e5f46f3be2f2.png)

**Comment by brianng0305** [comment]
thank you very much.
