### ISSUE TITLE
door assembly example is impossible to follow

### ISSUE THREAD

**Issue by greyltc** [CadQuery/cadquery#589]
The vslot-2020_1.dxf file is nowhere?
https://github.com/CadQuery/cadquery/blob/4c77c87eac9ec845a5a17cdd0acad745e938e4b9/doc/assy.rst#L28

**Comment by jmwright** [comment]
I think this is the download link: https://www.matronics.dk/data/longship/files/products/vslot-2020_1.dxf

**Comment by adam-urbanczyk** [comment]
Solved by https://github.com/CadQuery/cadquery-contrib/commit/1460cb2adab208a7614c9d55762458d93e5ba843
