### ISSUE TITLE
cannot draw 2D square 

### ISSUE THREAD

**Issue by brianng0305** [CadQuery/cadquery#605]
I cannot draw double square in 2d format
`layout = cq.Workplane().rect(100,100).rect(90,90)`
![Screenshot from 2021-01-29 10-19-29](https://user-images.githubusercontent.com/36631693/106223191-eb860500-621b-11eb-8806-2cdd4ce6ae70.png)

But it works for extrude
`layout = cq.Workplane().rect(100,100).rect(90,90).extrude(10)`
![Screenshot from 2021-01-29 10-18-30](https://user-images.githubusercontent.com/36631693/106223201-f0e34f80-621b-11eb-8524-33013aaa5da4.png)

**Comment by marcus7070** [comment]
This is part of the internals of CadQuery.

CQ-editor shows what is currently in a Workplane's objects attribute.

After `layout = cq.Workplane().rect(100,100)`, the `layout.objects` list contains one square, and that square is also appended to the `layout.ctx.pendingWires` list.

After the second square, ie. `layout = cq.Workplane().rect(100,100).rect(90,90)`, the `layout.objects` list contains just one 90x90 square, and that square is also appended to the `layout.ctx.pendingWires` list (which now contains both squares). Extrude uses the `layout.ctx.pendingWires` list, while CQ-editor just displays the current `layout.objects`.

**Comment by adam-urbanczyk** [comment]
If you _really_ need to see both at once you can consolidate them.
```
res = cq.Workplane().rect(1,1).rect(3,3).consolidateWires()
```
