### ISSUE TITLE
show_object does not support option parameter

### ISSUE THREAD

**Issue by tolot27** [CadQuery/cadquery#62]
In QC1.2 show_object allows to pass an option parameter, i. e. to set the color and transparency of the shape (`show_object(result, options={"rgba":(128, 255, 128, 0.0)})`). Unfortunately, this parameter is not available in cadquery-occ and the following error occurs:

```
TypeError: () got an unexpected keyword argument 'options'
```

I know, there are likely still a lot of incompatibilities yet between QC1.2 and QC-occ. Will they be solved in the future such as a direct upgrade without much code adjustments would be possible?

**Comment by adam-urbanczyk** [comment]
Yes, that is definitely our ambition

**Comment by adam-urbanczyk** [comment]
Should be fixed by #86. @jmwright  could you confirm?

**Comment by jmwright** [comment]
Yes, when #86 is merged it should fix this. It's still WIP for now though. I'm struggling to get an environment set up so I can run the test suite locally, but after I figure that out the progress on this should be pretty quick.

**Comment by jmwright** [comment]
@tolot27 If you're still watching this issue, this should be fixed in the adam-urbanczyk-OCC-version-update branch.

If you're interested in trying it, let us know if you want any help getting set up.

**Comment by jmwright** [comment]
Closing this. The fix isn't in master yet, but is accessible now on a branch and will be in master at some point.

**Comment by tolot27** [comment]
@adam-urbanczyk Can you merge the fix into master? The branch is no longer available.

**Comment by tolot27** [comment]
See [CQ-editor doesn't recognize show_object() options variable](https://groups.google.com/forum/#!msg/cadquery/eQbwXNyiQ7U/hLXkWe6sCgAJ)
