### ISSUE TITLE
Missing file in Assembly tutorial

### ISSUE THREAD

**Issue by MarcWeber** [CadQuery/cadquery#622]
https://cadquery.readthedocs.io/en/latest/assy.html
I cannot find vslot-2020_1.dxf. I searched Google, github and this git repository, gihtub open issues.

**Comment by jmwright** [comment]
@MarcWeber Please see the comment here: https://github.com/CadQuery/cadquery/issues/589#issuecomment-762639965

**Comment by adam-urbanczyk** [comment]
It is available here https://github.com/CadQuery/cadquery-contrib/tree/master/examples
