### ISSUE TITLE
check edges before doing chamfer

### ISSUE THREAD

**Issue by KammutierSpule** [CadQuery/cadquery#64]
Is possible to somehow check the edges before doing a chamfer to see if is possible?

```
File "/home/kammutierspule/anaconda3/envs/testenv/lib/python3.6/site-packages/cadquery/cq.py", line 889, in chamfer
    s = solid.chamfer(length, length2, edgeList)
File "/home/kammutierspule/anaconda3/envs/testenv/lib/python3.6/site-packages/cadquery/freecad_impl/shapes.py", line 994, in chamfer
    return Shape.cast(self.wrapped.makeChamfer(length, nativeEdges))
```

**Comment by jmwright** [comment]
@KammutierSpule I'm not aware of any way that is built-in. You can pull the edges out yourself and check them manually though before performing the operation.
```python
import cadquery as cq

def _handle_edges(edge):
	print("Start Point:" + str(edge.startPoint()) + ", End Point:" + str(edge.endPoint()))

result = cq.Workplane("XY").rect(10, 10).extrude(10)

edges = result.faces(">Z").edges()
edges.each(_handle_edges)

show_object(result, options={"rgba":(204, 204, 204, 0.0)})
```
There may also be a check if you extract the FreeCAD object so that operations can be performed on that. I'm not overly familiar with the lower level FreeCAD operations though.

**Comment by KammutierSpule** [comment]
Hi Jeremy,
I'm new to python to excuse my possible basic questions.
this error I got is with FreeCAD implementation but as far as I understand you are porting it to use PythonOCC. That will be a different check implementation in future?

How do I know ( python question ) what is that edge class and its methods ( as startPoint.. endPoint )?

Finally, what is really the error here? Could it be because start point and end point are the same?
I suspect that it may also be because the faces().edges() return a list of edges that after apply a chamfer, that edges will no longer exist ( or could be overlapped ? )

Is it possible somehow with other operations and constructions ( eg using a box and cut operation ) to do something similar to a chamfer and apply a cut to the object?

**Comment by KammutierSpule** [comment]
My script is generating random stuff ( unions and cuts, etc ) so it may be generating invalid cases for chamfer while selecting all the edges.
I will investigate a bit more and avoid this kind of operations for now.
Thanks for your tips, I will close the issue.
