### ISSUE TITLE
Origin of the workplane of non centered box.

### ISSUE THREAD

**Issue by ikeji** [CadQuery/cadquery#642]
I wrote this code:
```
length = 80.0
height = 60.0
thickness = 10.0
center_hole_dia = 22.0

result = (cq.Workplane("XY").box(length, height, thickness,(False,False,False))
    .faces(">Z").workplane().hole(center_hole_dia))
```

I run this code in CQ-Editor that download from CI.
https://github.com/jmwright/CQ-editor/actions

When I run this code in CQ-Editor build 48 (build on Mon, 30 Nov 2020 19:14:31 GMT),
It created this model.

![build48](https://user-images.githubusercontent.com/38523/107963240-432dba00-6feb-11eb-8c42-f14013028229.png)

When I run this code in CQ-Editor build 50 (build on Wed, 20 Jan 2021 18:43:37 GMT),
it created this model.

![build50](https://user-images.githubusercontent.com/38523/107963454-8be57300-6feb-11eb-9312-77bf4fbce634.png)

Is this change intended?
I'm afraid this change back again?

**Comment by adam-urbanczyk** [comment]
Yes, take a look at `changes.md` and #532  - the default `centerOption` changed. You can go back to the old behavior like so:
```python
length = 80.0
height = 60.0
thickness = 10.0
center_hole_dia = 22.0

result = (cq.Workplane("XY").box(length, height, thickness,(False,False,False))
    .faces(">Z").workplane(centerOption='CenterOfMass').hole(center_hole_dia))
```

**Comment by ikeji** [comment]
Thanks!
