### ISSUE TITLE
Spelling mistakes in Class Summary documentation

### ISSUE THREAD

**Issue by themrdjj** [CadQuery/cadquery#658]
The word "wither" appears three times on https://cadquery.readthedocs.io/en/latest/classreference.html. I believe this should be "whether", right? I'm quite new to open source software, can I submit a pull request myself by forking and editing this in https://github.com/CadQuery/cadquery/blob/master/cadquery/cq.py?

**Comment by jmwright** [comment]
> I believe this should be "whether", right?

Yes, good catch.

> I'm quite new to open source software

Welcome.

> can I submit a pull request myself by forking and editing this in

Yes, you fork the cadquery repo, clone your fork to your computer, make the changes, push those changes to your fork, then open a PR. We'll work with you on the PR if anything needs to be changed (our core dev team is welcoming of newcomers and PRs), then we'll merge. I can answer other questions about the process if you have any.
