### ISSUE TITLE
MyPy Error in master CI

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery#669]
```
$ mypy cadquery
cadquery/occ_impl/shapes.py:159: error: Module 'OCP.Font' has no attribute 'Font_BRepTextBuilder'
```

I think this might be caused by the [recent commit](https://github.com/CadQuery/OCP-stubs/commit/51932c145b16af53fed202ea4d6896263249d8b4) in OCP-stubs. I'm probably going to pin the version to the 7.4.0 tag for now to see if that fixes the builds.

**Comment by jmwright** [comment]
Pinned the OCP-stubs version to tag 7.4.0 in commit d350c1b81a7770921a3d04f8c8639fc4a4ff5a7c

We will need to revert that when moving to OCCT/OCP 7.5.0

**Comment by adam-urbanczyk** [comment]
Solved - pinned stubs to OCP7.5.1
