### ISSUE TITLE
DOI Badge Is Broken

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery#743]
I noticed that the DOI badge in the readme was just displaying text instead of an image, and looked into it. It looks like the links for the badge SVG and the URL the badge points to have changed.

Old DOI Badge Markdown:
```
[![DOI](https://zenodo.org/badge/155099400.svg)](https://zenodo.org/badge/latestdoi/155099400)
```

New DOI Badge Markdown:
```
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4498634.svg)](https://doi.org/10.5281/zenodo.4498634)
```
I clicked on the DOI badge in the right sidebar [here](https://zenodo.org/record/4498634) to get the new information. I can change it, but wasn't involved in adding the DOI badge and I wanted to make sure I wasn't missing something.

**Comment by fedorkotov** [comment]
Is it really fixed? This is what I see (Firefox 88.0 64-bit, Windows 8.1)
![image](https://user-images.githubusercontent.com/1106650/116392906-b17fcb80-a829-11eb-89e7-294d54a5e6bb.png)

**Comment by jmwright** [comment]
@fedorkotov  I wasn't paying attention and didn't get that change committed with the other PR. I've fixed it and CI is running on the merge right now. If it's not fixed after CI has finished, I'll edit directly on GitHub so that I can use the preview.

**Comment by jmwright** [comment]
So the link is updated in the badge now, but it seems we're not alone in having the badge refuse to display.

https://github.com/zenodo/zenodo/issues/2165

There are a couple of odd things in their generated SVG file. I may experiment with that a little bit.

**Comment by fedorkotov** [comment]
> There are a couple of odd things in their generated SVG file

It takes 26 seconds to load from where I am (Moscow, Russia).
After it is finally loaded it looks ok
![image](https://user-images.githubusercontent.com/1106650/116403943-d3cc1600-a836-11eb-85a5-d73401b823b8.png)
```xml
<svg xmlns="http://www.w3.org/2000/svg"
     width="186" height="20">
        <linearGradient id="b" x2="0" y2="100%">
            <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
            <stop offset="1" stop-opacity=".1"/>
        </linearGradient>
        <mask id="a" width="186" height="20">
            <rect width="186" height="20" rx="3"
            fill="#fff"/>
        </mask>
        <g mask="url(#a)">
            <path fill="#555" d="M0 0h31v20H0z" />
            <path fill="#007ec6"
            d="M31 0h155v20H31z"
            />
            <path fill="url(#b)" d="M0 0h186v20H0z" />
        </g>
        <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,
        Verdana,Geneva,sans-serif" font-size="11">
            <text x="16" y="15" fill="#010101"
            fill-opacity=".3">
                DOI
            </text>
            <text x="16" y="14">
                DOI
            </text>
            <text x="108"
            y="15" fill="#010101" fill-opacity=".3">
                10.5281/zenodo.4498634
            </text>
            <text x="108" y="14">
                10.5281/zenodo.4498634
            </text>
        </g>
    </svg>
```

**Comment by jmwright** [comment]
It's taking about that long for the image to load for me in the US too. Maybe GitHub is timing out while trying to load the image? 

I tried uploading the SVG to my own web server and it loads fine in the readme. I guess I'll change the readme to point to the temporary image location and leave this issue open so we can circle back when Zenodo has their issue fixed.

**Comment by jmwright** [comment]
Ok, change made and badge is visible again. Thanks for the feedback on this issue @fedorkotov

**Comment by jmwright** [comment]
Looks like there might be a content header issue on Zenodo's side in addition to the long load times.

https://github.com/zenodo/zenodo/issues/2165#issuecomment-829109421

**Comment by jmwright** [comment]
This appears to be fixed now on Zenodo's side, although there has been no communication on what happened. The issue was closed and the badge SVG now works.

**Comment by adam-urbanczyk** [comment]
Thanks for looking into this @jmwright !
