### ISSUE TITLE
Workplane polygon documentation - minimum number of sides

### ISSUE THREAD

**Issue by trayracing** [CadQuery/cadquery#747]
For workplane.polygon, there's a small error in the documentation:
`nSides (int) – number of sides, must be > 3`
should be `>= 3`

Thanks

**Comment by fedorkotov** [comment]
@himanshu007-creator I am not a maintainer of this project but I think you can just create a pull request and mention this issue in commit message. No need to wait for formalities. See also https://github.com/CadQuery/cadquery#contributing-code
