### ISSUE TITLE
Allow rect to have negative lengths to reverse direction (much like extrude)

### ISSUE THREAD

**Issue by willhansen** [CadQuery/cadquery#773]
Right now, the rect function only extends the rectangle in the positive x and y directions.  It would be convenient to be able to give negative numbers to extend in the opposite directions, like how extrude works.  (e.g.  extrude(5) vs extrude(-5))

Current documentation for rect: [here](https://cadquery.readthedocs.io/en/latest/classreference.html#cadquery.Workplane.rect)
(Note the "float > 0" restrictions for the xLen and yLen parameters)

**Comment by marcus7070** [comment]
Thanks @willhansen. Negative `xLen` and `yLen` do actually work right now (with `centered=False` or `(True, False)`).

```python
result = cq.Workplane().rect(1, -1, centered=(True, False))
```

![screenshot2021-05-24-144606](https://user-images.githubusercontent.com/50230945/119300071-4a75fb00-bc9f-11eb-924a-f891a3406fed.png)

I completely missed that use case when I last rewrote that method, it's a bit of a fluke that it works. The docs need to be fixed like you point out, and this use case needs to have some tests written for it.
