### ISSUE TITLE
Handpicking from STEP Assembly

### ISSUE THREAD

**Issue by infosisio** [CadQuery/cadquery#784]
I am able to create an assembly in CQ from scratch and export that to an STEP. 

How do I deal with the case though where I am given an STEP assembly from someone and I want to handpick solids from it, in order to compose a new assembly or do further work?

Is there support for something like this?

**Comment by adam-urbanczyk** [comment]
Currently STEP is imported as a `cq.Workplane` - you can select solids using CQ selectors.

**Comment by infosisio** [comment]
@adam-urbanczyk Ok, thanks. Is there a quick example you could share for that?

**Comment by jmwright** [comment]
It's not documented and not used a lot (as far as I know), but here's a simple example using the door assembly in the docs.

```python
import cadquery as cq

door = cq.importers.importStep('door_assy.step')

bottom = door.solids("<Z")

corner2 = door.solids(cq.selectors.NearestToPointSelector((0, 0, 0)))

show_object(corner2)
```
Not all selectors will work with solids, and some don't work in an intuitive way.
