### ISSUE TITLE
Workplane center

### ISSUE THREAD

**Issue by parnold-x** [CadQuery/cadquery#785]
Hi, if I try the example of center in the method documentation
s = cq.Workplane().box(1,1,1).faces(">Z")
s=s.center(-0.5,-0.5)
s=s.circle(0.25).extrude(0.2)

I get this result
![image](https://user-images.githubusercontent.com/3041711/121380242-004e7400-c945-11eb-9c46-1144bdc4eb81.png)

I expected that the new origin of the workplane would be the top left corner. Am I missing something?

**Comment by Jojain** [comment]
Why would you think the center would be in the top left corner ? The workplane center is, after the box operation, in (0,0,0)  you moved it in (-0.5,-0.5,0) so it makes sense to get your result

**Comment by parnold-x** [comment]
Ok, thank you. Then it works.

**Comment by adam-urbanczyk** [comment]
You probably wanted:
```python
s = cq.Workplane().box(1,1,1).faces(">Z").workplane()
s=s.center(-0.5,-0.5)
s=s.circle(0.25).extrude(0.2)
```
