### ISSUE TITLE
one surface with different color with pythonocc

### ISSUE THREAD

**Issue by liuxin2322** [CadQuery/cadquery#80]
just like this.  how to realize it ?
![在这里插入图片描述](https://img-blog.csdnimg.cn/20190106140149168.?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80Mjc1NTM4NA==,size_16,color_FFFFFF,t_70)

**Comment by jmwright** [comment]
See #60

While CadQuery doesn't have good support for surfaces yet, there might be lower level PythonOCC functionality that you can access to do what you want. You can mix PythonOCC syntax with CadQuery syntax since they're both based on Python.

**Comment by adam-urbanczyk** [comment]
I think you need to experiment with this class from PythonOCC: https://www.opencascade.com/doc/occt-6.9.0/refman/html/class_a_i_s___textured_shape.html . Unfortunately I have no experience with it. Please also note that this is visualization related class (i.e. `AIS_*`).  

I will close this issue for now.
