### ISSUE TITLE
Multi-section sweep can self-intersect

### ISSUE THREAD

**Issue by tanius** [CadQuery/cadquery#808]
The method `Workplane::.sweep(path, multisection = True)` uses a kind of interpolation to achieve a smooth transition between the wires used for each section. Visually, it seems to be spline-based interpolation. Now depending on the wires provided for each section and their distances, this interpolation may result in self-intersecting and thus non-manifold shapes.

Here's example code with a screenshot. Green is a case where result matches expectation, red is a case where the parameter values were tunes just a bit more, resulting in a self-intersecting shape.

![image](https://user-images.githubusercontent.com/843907/123819653-3ce50e00-d8fa-11eb-997b-e6c0f0f08f23.png)

```python
import cadquery as cq

path = cq.Workplane("XY").lineTo(0, 30).wire()

good_model = (
    cq.Workplane("XY")

    .pushPoints([path.val().locationAt(0)]).rect(4, 5)
    .pushPoints([path.val().locationAt(0.5)]).rect(4, 5)
    .pushPoints([path.val().locationAt(0.7)]).rect(4, 8)
    .pushPoints([path.val().locationAt(1)]).rect(4, 8)

    .consolidateWires()
    .sweep(path, multisection = True)

    .translate((0, 0, -10))
)

show_object(good_model, options = {"color": "green", "alpha": 0.8})

bad_model = (
    cq.Workplane("XY")

    .pushPoints([path.val().locationAt(0)]).rect(4, 5)
    .pushPoints([path.val().locationAt(0.5)]).rect(4, 5)
    .pushPoints([path.val().locationAt(0.7)]).rect(4, 13)
    .pushPoints([path.val().locationAt(1)]).rect(4, 13)

    .consolidateWires()
    .sweep(path, multisection = True)
)

show_object(bad_model, options = {"color": "red", "alpha": 0.8})
```

**Comment by adam-urbanczyk** [comment]
In such a case you'll need to specify more intermediate cross-section

**Comment by tanius** [comment]
Thank you – yes, adding intermediate cross-sections works. Though I found it's then still a challenge to anticipate how the interpolation will behave. And with many intermediate cross-sections, model calculation takes significantly longer.

What I also tried is doing the multi-section sweep pairwise between two wires each and then combining the resulting solids into one. This creates a linear interpolation between corresponding corners of two adjacent profiles, without the overshoot that can be produced by spline-based interpolation. Maybe that could be supported as another mode of multi-section sweeps in the `sweep()` method?

On a more general note: when (like here) a CadQuery operation generates a non-manifold shape, do you always consider this to be a bug or not? I had assumed so, but maybe that's not how you see it.

**Comment by adam-urbanczyk** [comment]
If you have a straight spine you can use loft with `ruled=True`. 

You'll be always able to generate incorrect geometries with a B-rep kernel, so I wouldn't consider this a bug.
