### ISSUE TITLE
`Shell.makeShell` doesn't appear in HTML docs

### ISSUE THREAD

**Issue by marcus7070** [CadQuery/cadquery#814]
The method doesn't appear in the auto generated docs.

https://cadquery.readthedocs.io/en/latest/classreference.html#cadquery.Shell

Other class methods do, not sure what's special about makeShell.

**Comment by lorenzncode** [comment]
Looks like makeShell is skipped due to missing docstring.

**Comment by marcus7070** [comment]
Oh, of course, thanks.
