### ISSUE TITLE
docs HTML API reference duplicates Parameter lists

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/cadquery#819]
See the HTML reference for Workplane.lineTo as an example:

https://cadquery.readthedocs.io/en/latest/classreference.html#cadquery.Workplane.lineTo

![lineTo_current](https://user-images.githubusercontent.com/16394272/124858878-dfe1fb80-df7c-11eb-986a-18c48460f66d.png)

Notice there are two "Parameters:" lists where one list per method is expected.  Here is the portion of the lineTo docstring that documents parameters:

```
    :param float x: the x point, in workplane plane coordinates
    :param float y: the y point, in workplane plane coordinates
    :return: the Workplane object with the current point at the end of the new line
```

sphinx-build is currently configured to use the 3rd party extension "sphinx_autodoc_typehints".  
The docstring param definitions are expected to be of the form:

```
    :param x: the x point, in workplane plane coordinates
```

Modified docstring:

        """
        Make a line from the current point to the provided point

        :param x: the x point, in workplane plane coordinates
        :param y: the y point, in workplane plane coordinates
        :param forConstruction: whether or not the edge is used only for reference
        :return: the Workplane object with the current point at the end of the new line

        see :py:meth:`line` if you want to use relative dimensions to make a line instead.
        """

(I'm not sure if forConstruction should be documented or not - this is an example)
Re-running sphinx-build now yields:

![lineTo2](https://user-images.githubusercontent.com/16394272/124859178-68609c00-df7d-11eb-9a5b-1a69635c1168.png)

The docs are still corrupted and contain a second Parameters: list (single item self).  I find this **second list is created due to sphinx_autodoc_typehints** option set in conf.py:
**```always_document_param_types = True```**

Commenting this out or setting to False yields:

![lineTo3](https://user-images.githubusercontent.com/16394272/124859258-9514b380-df7d-11eb-871c-2efcdac466ac.png)

Many of the API reference methods have this issue with multiple Parameters lists. Not all of them (such as intersect) because in those cases there is no other text description in the docstring after the first parameter list.  The extension creates the stub for self, and other args and they become part of the first list.

One option to clean up the API reference is to disable ```always_document_param_types``` and continue using the sphinx_autodoc_typehints extension along with making docstring updates.

The above was generated with sphinx 3.2.1 (pinned in environment.yml).  Sphinx has built-in autodoc_typehints and I ran a few experiments with Sphinx 4.0.3 (same modified docstring as above).  The following is no longer using the sphinx_autodoc_typehints extension.

First with: ```autodoc_typehints = 'none'```:

![lineTo5](https://user-images.githubusercontent.com/16394272/124859457-f76db400-df7d-11eb-8cd0-eb105a1edeaa.png)

With ```autodoc_typehints = 'description'```:

![lineTo6](https://user-images.githubusercontent.com/16394272/124859473-02c0df80-df7e-11eb-982a-8d732dc481f0.png)

Sphinx built-in typehint still adds "self" but handles it better than the other extension.  self is added to the Parameters list but at least we don't have two lists.  

Setting:
```
autodoc_typehints = 'description'
autodoc_typehints_description_target = 'documented'
```

![lineTo7](https://user-images.githubusercontent.com/16394272/124859617-3e5ba980-df7e-11eb-8ed5-c810201453f9.png)

**Comment by marcus7070** [comment]
I think the following line in sphinx-autodoc-typehints should be dropping off the first parameter (`self`): https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L245
but it doesn't.

**Comment by marcus7070** [comment]
> I think the following line in sphinx-autodoc-typehints should be dropping off the first parameter (`self`): https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L245
> but it doesn't for `Workplane.text` and the other examples.

I misread, that's the function that process the signature, not the docstring, which is [here](https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L407-L474).

The signature processing function does drop the first argument, the docstring function does not. :confused:

**Comment by lorenzncode** [comment]
I find that it's dropped (the first parameter ```self```) only when there is no self-type.  

Testing with dummy input:

```
T = TypeVar("T", bound="MyClass1")
"""A type variable used to make the return type of a method the same as the
type of `self` or another argument.
"""

class MyClass1(object):

    """ My class 1 """

    def method1(self: T, arg1: bool = True) -> int:

        """
        This is method1

        :param arg1: this is arg1
        :return: 1 

        Example

        """

        return  1


class MyClass2(object):

    """ My class 2 """

    def method1(self, arg1: bool = True) -> int:

        """
        This is method1

        :param arg1: this is arg1
        :return: 1 

        Example

        """

        return  1

```

Extension sphinx_autodoc_typehints:

![sphinx_autodoc_typehints](https://user-images.githubusercontent.com/16394272/125005175-22f9a880-e029-11eb-8c83-e3e1e3623194.png)

sphinx built-in:

![sphinx_builtin](https://user-images.githubusercontent.com/16394272/125005235-4b81a280-e029-11eb-8ccd-b13d86acf647.png)

**Comment by lorenzncode** [comment]
The following will strip out the self param added by extension sphinx_autodoc_typehints.

```
from sphinx.ext.autodoc import between

def setup(app):
    app.connect('autodoc-process-docstring', between(marker=".*self:", what=['method'], exclude=True))
```

Note that while it does remove self, it does not solve the issue of duplicate Parameter lists.  For example, this docstring does not explicitly list arg2.

```
    def method1(self: T, arg1: bool = True, arg2: str = "X") -> int:

        """
        This is method1

        :param arg1: this is arg1
        :return: 1 

        Example

        """

        return  1
```

Result:

![arg2undocumented](https://user-images.githubusercontent.com/16394272/125020017-10419c80-e046-11eb-9b06-5693cad32bb4.png)


As mentioned, Sphinx built-in handles this case better (once we figure out how to exclude self):

![arg2undocumented_sphinx](https://user-images.githubusercontent.com/16394272/125020591-20a64700-e047-11eb-92a5-455b4ee32b92.png)

Modifying the Sphinx built-in type hints to exclude self looks like it would be a different process.  "between" cannot be used as I find a different method is used than the extension (it does not change the docstring itself as sphinx_autodoc_typehints does).

**Comment by marcus7070** [comment]
This might work with Sphinx's inbuilt autodoc:

```python
def drop_self(app, obj, bound_method):
    if hasattr(obj, "__annotations__"):
        obj.__annotations__.pop("self", None)


def setup(app):
    app.connect("autodoc-before-process-signature", drop_self)
```

I haven't checked what other type hinting this might wipe out.

**Comment by marcus7070** [comment]
Before we go any further, can @adam-urbanczyk and @jmwright just let me know their opinions.

![](https://user-images.githubusercontent.com/16394272/124858878-dfe1fb80-df7c-11eb-986a-18c48460f66d.png)

Regarding the HTML docs for `Workplane` methods:
1. Should `self` be in the signature?
2. Should `self: ~T` be in the parameters list?
3. Should `~T` be the return type?

I'd say 1: no, 2: no, 3: yes but we need a note at the top that `~T` is a TypeVar bound to Workplane.

**Comment by adam-urbanczyk** [comment]
I'm for 2+3

**Comment by marcus7070** [comment]
Ok @lorenzncode, I think the style to aim for is to have one autodoc list with:
```
Parameters:
  - self (~T)
 ...
Return type:
  - ~T
```

I don't have a strong opinion on how we get there, but I'd suggest we just correct any `:param float:` lines and move all `:param` and friends to the bottom of docstrings. I think that will fix all the issues you've identified, right?

**Comment by lorenzncode** [comment]
We could substitute "Workplane" for "~T" by specifying the alias using autodoc_type_aliases.  Here is a screenshot with RTD version on left and local build on right. 

![image](https://user-images.githubusercontent.com/16394272/126420661-fe109a7d-56dd-4873-9c4b-c18e141c7fee.png)

I like this solution (use built-in sphinx instead of additional extension) as it fixes the corrupt document structure (duplicate Parameter lists) without requiring any changes to the docstrings!

**Comment by marcus7070** [comment]
Sounds good to me. I see @jmwright approves, @adam-urbanczyk do you mind if we do a PR to try replacing the sphinx-autodoc-typehints extension with Sphinx' inbuilt autodoc?

**Comment by lorenzncode** [comment]
Another example comparing Workplane.polyline.  Current docs:

![Screenshot from 2021-10-29 23-12-09](https://user-images.githubusercontent.com/16394272/139518399-fd71a4a1-8460-4552-bd63-4fc8d8397ebc.png)

Updated:
![Screenshot from 2021-10-29 23-09-45](https://user-images.githubusercontent.com/16394272/139518460-7beff8c3-5fc1-41cd-b06f-5521654133d7.png)

As with each() the signature is more verbose than the existing docs.

**Comment by lorenzncode** [comment]
I got side-tracked investigating the `autodoc_type_aliases` feature which is not necessary to address the problem of this issue.  I'd like to keep it simple and move forward to resolve this duplicate parameters in the HTML docs issue.


Proposed changes:

- Remove dependency on the current package used for doc typehints.  The Sphinx built-in extension can replace it to resolve this issue.  No other hooks or customization are required.  

- Update the sphinx version pin to current version

- Set the following sphinx autodoc config options: 

  `autodoc_typehints = "both"`

  This option is new in sphinx 4.1 and shows the typehints in the signature and as content of the function or method.

  `autodoc_typehints_description_target = "all"`

  This follows the current behavior but can be changed to `documented` if that is preferred.  See for example the current Workplane.line() doc.  The HTML shows `forConstruction` in the Parameter list even though it is not documented.
  

You can expect some presentation differences in the doc update compared to the old version.  For example, the built-in sphinx autodoc_typehints will show the qualified name `cq.occ_impl.shapes.Face` instead of `Face` and the typehints will now be hyperlinks.


See the following example for cutBlind. 

current docs:
![Screenshot from 2021-11-02 19-43-18mod](https://user-images.githubusercontent.com/16394272/139967298-c61ea11c-ca9a-4617-918f-0b5fb735c0f7.png)


with changes:

![Screenshot from 2021-11-02 19-53-47](https://user-images.githubusercontent.com/16394272/139967392-b2ecc493-6fd6-4dd3-9a23-3bffc559c078.png)

**Comment by jmwright** [comment]
This seems like a reasonable path forward. +1

**Comment by lorenzncode** [comment]
Great.  BTW, regarding `autodoc_typehints = "both"` - it could be reverted to "description" later if we want to match the current docs more closely.  I chose "both" because "signature" is the sphinx default and cadquery currently adds typehints to description.  

"both" may be useful for cases such as Workplane.polyline() where the optional type comment is shown in the description based on docstring: 

`:type listOfXYTuple: list of 2-tuples`

and then the type is shown in the signature as: 

`listOfXYTuple: Sequence[Union[Tuple[float, float], Tuple[float, float, float], cadquery.occ_impl.geom.Vector]]`

In the future perhaps this could also be simplified with type_aliases.
