### ISSUE TITLE
vim / neovim - autocomplete stop working after seven repetitions

### ISSUE THREAD

**Issue by ardaij** [CadQuery/cadquery#823]
I use vim / nvim as editor. The code to completion working.
But if something happens seven times in a program, this stopped working.

For example:

import cadquery as cq
part = (cq.Workplane("XY")
        .circle(10)
        .extrude(10)
        .faces(">Z")
        .circle(10)
        .extrude(10)
        .faces(">Z")
        .circle(10)
        .extrude(10)
        .faces(">Z")
        .circle(10)
        .extrude(10)
        .faces(">Z")
        .circle(10)
        .extrude(10)
        .faces(">Z")
        .circle(10)
        .extrude(10)
        .faces(">Z")
        .circle(10)
        )

After the seventh ".circle()", (or seventh .lineTo(), etc. ) the code completion stop working.
I tried this with several add-ons, always the same result.

"davidhalter/jedi-vim",     "ncm2/ncm2-jedi"

**Comment by fedorkotov** [comment]
This is not a CadQuery problem. You probably should report this to vim/nvim developers or to developers of whatever auto-completion plugin you are using with it.

**Comment by adam-urbanczyk** [comment]
The code is valid Python, so closing.
