### ISSUE TITLE
`Workplane.shell` docstring needs updating

### ISSUE THREAD

**Issue by marcus7070** [CadQuery/cadquery#828]
https://github.com/CadQuery/cadquery/blob/ab876acc84a7df273bb368549656912a980feae3/cadquery/cq.py#L1225-L1234

Needs to be updated to use the `or` string selector, fluent api, and remove the `saveModel` call.

**Comment by lorenzncode** [comment]
As part of this, I think the add() docstring also needs an update to remove "Shelling is one common example" in:

>         Used in rare cases when you need to combine the results of several CQ
>         results into a single Workplane object. Shelling is one common example.
