### ISSUE TITLE
The script in Assemblies Doc 

### ISSUE THREAD

**Issue by zxo102** [CadQuery/cadquery#840]
With latest version of cadquery and cq-editor on my Windows 10, the script in [Assemblies](https://cadquery.readthedocs.io/en/latest/primer.html?highlight=tidy_repr#assemblies)
```
from cadquery import *
w = 10
d = 10
h = 10
part1 = Workplane().box(2*w,2*d,h)
part2 = Workplane().box(w,d,2*h)
part3 = Workplane().box(w,d,3*h)
assy = (
    Assembly(part1, loc=Location(Vector(-w,0,h/2)))
    .add(part2, loc=Location(Vector(1.5*w,-.5*d,h/2)), color=Color(0,0,1,0.5))
    .add(part3, loc=Location(Vector(-.5*w,-.5*d,2*h)), color=Color("red"))
)
```
results in 

![assemblies01](https://user-images.githubusercontent.com/9945043/128107188-2ba926a0-6abc-4421-8d96-3e84bcffadfe.jpg)

which is different from the output in [Assemblies](https://cadquery.readthedocs.io/en/latest/primer.html?highlight=tidy_repr#assemblies)
![assemblies02](https://user-images.githubusercontent.com/9945043/128107482-533f8bb8-98a4-489e-9ad5-d564f49d48ec.jpg)

**Comment by zxo102** [comment]
Adding  "show_object(assy)" at end returns the normal one :))
![assemblies03](https://user-images.githubusercontent.com/9945043/128114847-db1ea70e-a4b5-48f4-89b6-fabd0e8d7903.jpg)

**Comment by jmwright** [comment]
@zxo102 Yes, you need `show_object()` to display an assembly correctly. Otherwise CQ-editor does its magic to infer which objects you want to display and ignores their assembly attributes.

You have to use `toCompound()` when exporting an assembly to STL because the STL format does not support assemblies like the STEP format does.

```python
from cadquery import *

w = 10
d = 10
h = 10

part1 = Workplane().box(2*w,2*d,h)
part2 = Workplane().box(w,d,2*h)
part3 = Workplane().box(w,d,3*h)
assy = (
    Assembly(part1, loc=Location(Vector(-w,0,h/2)))
    .add(part2, loc=Location(Vector(1.5*w,-.5*d,h/2)), color=Color(0,0,1,0.5))
    .add(part3, loc=Location(Vector(-.5*w,-.5*d,2*h)), color=Color("red"))
)

exporters.export(assy.toCompound(), 'assy.stl')
```

![Screenshot from 2021-08-06 07-24-11](https://user-images.githubusercontent.com/1015439/128503495-5a3dd20e-258d-43af-96e4-d8a409c8bd55.png)

**Comment by zxo102** [comment]
@jmwright  Thanks a lot for your help.

**Comment by zxo102** [comment]
@jmwright  How do you draw the grid on the XY plane with coordinates in the above output?

**Comment by jmwright** [comment]
@zxo102 That's a screenshot from PrusaSlicer, which is not a CadQuery project. I just wanted to show that the exported STL file comes out correctly.
