### ISSUE TITLE
show_object to build_object Reversion in CQGI

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery#85]
cqgi.py in this repo includes the `build_object` verbiage rather than the newer `show_object` verbiage. My guess is that the OCC branch was forked before the change from build -> show. I thought there was some work done on merging the latest updates from dcowden/master into the adam-urbanczyk-OCC-version-update branch. Was that ever done? Was `cadquery/cqgi.py` planned to be part of that?

**Comment by adam-urbanczyk** [comment]
I merged a lot of changes #65  Indeed `show_object` was missed there. Obviously I do want to have it merged.

**Comment by jmwright** [comment]
#86 addresses this as a PR, so I'm closing this issue.
