### ISSUE TITLE
Suggestion: rename (or alias) cboreHole and cskHole to counterbore and countersink

### ISSUE THREAD

**Issue by martinbudden** [CadQuery/cadquery#862]
The names `cboreHole` and `cskHole` are not really very satisfactory:

1. They are a bit obscure (especially `cskHole`)
2. (Pedantically) `cboreHole` is redundant: a bore is a hole
3. They are difficult to pronounce

I suggest we just use `counterbore` and `countersink`. The old names could be retained as aliases for compatibility if desired/required.

**Comment by adam-urbanczyk** [comment]
You are proposing an API change without a good reason.

**Comment by martinbudden** [comment]
@adam-urbanczyk The reason is code readability and code understandability.

And as I said, aliases could be used to retain compatibility.

**Comment by adam-urbanczyk** [comment]
Naming is very subjective and CQ is at v2.0. If it helps think about `cboreHole` as counterbored hole and `cskHole` as countersunk hole.
