### ISSUE TITLE
Bool ops/ add should merge tags on the Workplane level

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#888]
We want to merge the tags at the `cq.Workplane.ctx.tags` level and handle conflicts (e.g. tags defined in the left arg have precedence).

**Comment by lorenzncode** [comment]
I started to look into this.  Here is a union example:

```
a = cq.Workplane("YZ").cylinder(30,5).faces(">X").workplane().tag("xface")

b = cq.Workplane("YZ", origin=(6,0,0)).sketch().circle(8).circle(5.1, mode="s").finalize().extrude(6)

c = b.union(a.end(2))
c = c.workplaneFromTagged("xface").sketch().arc((0,0),5,45,90).close().assemble().finalize().cutBlind(-10)
```

![image](https://user-images.githubusercontent.com/16394272/142946633-1ea16b4f-36f4-43aa-9822-ea7ec7499b34.png)


Without union or tags:

```
a = cq.Workplane("YZ").cylinder(30,5).faces(">X").workplane()
a = a.center(4+1/2,0).sketch().rect(10,1).finalize().cutBlind(-10)

s_collar = cq.Sketch().circle(8).circle(5.1, mode="s")

a = a.faces(">X[-2]").workplane(offset=1, origin=(0,0,0))
a = a.placeSketch(s_collar).extrude(6)
```

**Comment by adam-urbanczyk** [comment]
What is the point you are trying to make?

**Comment by lorenzncode** [comment]
I just thought I would share progress before making a pull request - mostly to make sure I was on the same page here with what was expected.  Since the union example that requires merged tags was a bit contrived, I thought I would compare with an example that works today without the merged tags.

**Comment by adam-urbanczyk** [comment]
Thanks @lorenzncode , your first example works as expected.
