### ISSUE TITLE
How to slice a hollow cylinder using a sinusoidal profile?

### ISSUE THREAD

**Issue by safdark** [CadQuery/cadquery#893]
Say I have  cylinder:

```
cylinder = (
   cq.Workplane("XY")
   .circle(radius=10)
   .circle(radius=7)
   .extrude(distance=30)
)
```

I want to define a method, such as:
```
def sine_split(obj: cq.Workplane, at_height: float, sine_radius: float, edge_angle_degrees: int...) -> cq.Workplane():
   ...
```
... that cleanly splits the given cylinder along the sine curve, with the cut-edge itself tapering inward (or outward) depending on 'edge_angle_degrees'? Contextual parameters, such as cylinder radii etc, can be included, of course, as needed.

I'd like to get something like this:
![sinusoidal_cut_cylinder](https://user-images.githubusercontent.com/1193219/134969323-24719ae3-bd1e-4a1b-93c7-3f49aab0558e.png)

**Comment by adam-urbanczyk** [comment]
You can use `parametricSurface` and `split`.

**Comment by safdark** [comment]
Thanks @adam-urbanczyk . Will give it a try.
