### ISSUE TITLE
Does a tag operation survive a union() call?

### ISSUE THREAD

**Issue by threed-factory-store** [CadQuery/cadquery#898]
If I have an object separate from the "main" object and I tag a workplane on it, then I union this object with the main object, will the main object still have that tag?

From what I've seen, it does not.  But I'm very new to CadQuery.

**Comment by jmwright** [comment]
Related issue: https://github.com/CadQuery/cadquery/issues/888

**Comment by adam-urbanczyk** [comment]
Now it does - see #934 .
