### ISSUE TITLE
Merge changes from dcowden/cadquery

### ISSUE THREAD

**Issue by justbuchanan** [CadQuery/cadquery#9]
After sending #8, I realized that there are a lot of improvements and fixes in the main cadquery repo that haven't yet been merged into this one. While we could cherry-pick some of the most important changes, I think the best thing to do would be to merge dcowden/master into this repo (minus freecad_impl changes and any other freecad-related stuff) so we don't miss anything and preserve the git history. This is probably something to consider doing on a regular basis to avoid diverging too much.

If we do the merge, it will supersede #8 (which I've closed) as well as #1 and #6, in addition to adding many more improvements that have been contributed to the main repo since the pythonocc fork.

I'm happy to do the merge, but @adam-urbanczyk probably has better judgement on how to handle many of the merge conflicts (there are a lot - I have gotten about half way through them). Let me know what I can do to help and if you'd like me to send a PR with an attempt at the merge.

**Comment by adam-urbanczyk** [comment]
That is a tricky one. At least this change is in the freecad_impl so I will need to add it by hand I think.

I'll definitely try to merge the cadquery layer.

**Comment by justbuchanan** [comment]
Sounds good. I was actually surprised, but git seems to be smart enough to know that occ_impl/geom.py came from freecad_impl/geom.py, so doing a `git merge dcowden/master` does pull in the `Plane.__eq__()` changes and others into geom.py. There are many merge conflicts, but not too terrible.

**Comment by adam-urbanczyk** [comment]
For reference listing missing methods form cq.Workplane

name  | 0 
-- | -- 
copy | <bound method CQ.copy of <cadquery1.cq.Wor...
deepcopy | <bound method CQ.deepcopy of <cadquery1.cq...
intersect | <bound method Workplane.intersect of <cadquery...
polarArray | <bound method Workplane.polarArray of <cadquer...
polarLine | <bound method Workplane.polarLine of <cadquery...
polarLineTo | <bound method Workplane.polarLineTo of <cadque...
radiusArc | <bound method Workplane.radiusArc of <cadquery...
sagittaArc | <bound method Workplane.sagittaArc of <cadquer...
toFreecad | <bound method CQ.toFreecad of <cadquery1.cq.Wo...

**Comment by adam-urbanczyk** [comment]
I think this is solved by #65. Feel free to reopen if something pops up.
