### ISSUE TITLE
I want to use the pipeline function of cadquery to generate a model, but I don't know how to do it. 

### ISSUE THREAD

**Issue by luoyu-123** [CadQuery/cadquery#927]
I want to use the pipeline function of cadquery to generate a model, but I don't know how to do it. I am a beginner. I don't know where the pipeline function is, and there is no related function in the document. Please kindly ask for help, thank you very much.

The graphics are like this
![image](https://user-images.githubusercontent.com/59160360/144372627-c0bf0b09-a459-4f99-91dd-01c48b9e2d71.png)

**Comment by gumyr** [comment]
The functionality you are looking for is called `sweep` - here is an example:
```python
import cadquery as cq

# Create the path of the pipe from edges consolidated into a wire and convert to wire class
pipe_path = cq.Workplane("XY").hLine(10).vLine(10).consolidateWires().val()

# Create the pipe profile aligned with the beginning of the pipe path
pipe_outline = cq.Face.makeFromWires(
    cq.Wire.makeCircle(1, pipe_path.positionAt(0), pipe_path.tangentAt(0))
)

# Create the pipe by sweeping the profile along the path with "right" transtitions
pipe = cq.Solid.sweep(pipe_outline, pipe_path, transitionMode="right")

if "show_object" in locals():
    show_object(pipe_path, name="pipe_path")
    show_object(pipe_outline, name="pipe_outline")
    show_object(pipe, name="pipe")

```
This code results in the following:
![image](https://user-images.githubusercontent.com/85638518/144452210-73b2aabd-2f2d-4b12-bb04-22ec1332974a.png)

**Comment by luoyu-123** [comment]
Thank you very much for your enthusiastic help, but I don’t seem to be able to run your example, the error is reported as shown below

![image](https://user-images.githubusercontent.com/59160360/144541569-cb5380b9-60db-482d-a3ea-ce85ac8e8ee0.png)

**Comment by gumyr** [comment]
There have been some significant changes to cadquery master recently which I suspect are causing this problem for you. If you aren't using a very recent version of master, please reinstall cadquery and try again. You should check out the definition of Solid.sweep() on your systems (an IDE will help here) and ensure the parameters are correct. I'm guessing that on your system you'll need to replace the pipe assignment with this:
```python
pipe = cq.Solid.sweep(pipe_outline, [], pipe_path, transitionMode="right")
```
where the empty list is the `innerWires` parameter.

**Comment by jmwright** [comment]
@luoyu-123 I think you need to call sweep on the profile and pass it the path.

```python
pipe = pipe_outline.sweep(pipe_path, transitionMode="right")
```

**Comment by adam-urbanczyk** [comment]
There are many ways to skin this cat. On the latest master:
```python

import cadquery as cq


path = cq.Workplane("XZ").polyline([(0,0,),(0,5),(5,5)])
pipe = cq.Workplane("XY").circle(1).sweep(path)

show_object(pipe)
```
![image](https://user-images.githubusercontent.com/13981538/144642797-b55fbf71-4907-4ff4-b491-bd7c65e55dd8.png)```

**Comment by luoyu-123** [comment]
Thank you very much for your help, cadquery is a great open source project. Thank you so much
Problem has been solved

![image](https://user-images.githubusercontent.com/59160360/144692290-a3d8056d-2f87-4de3-919e-cd9febfa8333.png)



best wishes！
