### ISSUE TITLE
Sketch().rect() height and width reversed

### ISSUE THREAD

**Issue by FelisCorax** [CadQuery/cadquery#938]
`show_object(cq.Sketch().rect(20,10))` generates and displays a rectangle with a length of **10 along the X axis** and **20 along the Y axis**. This is contrary both to expectation and to the behavior of other functions.

For example:
`show_object(cq.Workplane().rect(20,10))` results in a rectangle with a length of 20 along the X axis and 10 along the Y axis, as expected.
`show_object(cq.Sketch().trapezoid(20,10,45))` results in an isosceles triangle with a length of 20 along the X axis and 10 along the Y axis. Once again, as expected.

For anyone suffering from the same problem, using `cq.Sketch().trapezoid(20,10,90)` as a means of generating an appropriately dimensioned rectangle appears to be a functional workaround that won't break when `Sketch().rect()` is fixed.

Note that I tested this in a fresh conda environment with cadquery and cq-editor installed immediately prior to posting this bug.

**Comment by marcus7070** [comment]
Thanks for reporting @FelisCorax.
