### ISSUE TITLE
Expose more API of BRepOffsetAPI_MakePipeShell

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#94]
Specifically allow the user to select transition modes:

![afbeelding](https://user-images.githubusercontent.com/13981538/52747873-2f5ab200-2fe5-11e9-9d40-b47ee188dbff.png)

Cf. https://opencascade.blogspot.com/2009/12/surface-modeling-part4.html

**Comment by jmwright** [comment]
Wondering if this will address #39

**Comment by adam-urbanczyk** [comment]
I think it will
