### ISSUE TITLE
CadQuery at FOSDEM 2022

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery#957]
I will be giving a [presentation](https://fosdem.org/2022/schedule/event/cadquery/) at FOSDEM 2022 with a short Q&A after. The times on the schedule are GMT+1 according to the organizers.  I'll be talking about what CadQuery is, briefly highlighting the new Sketch feature, and then talking about many of the projects going on within the community. There is a chat room for the devroom the presentation is in, and it would be great if we can have a small community presence there in case there are questions (although I can't sign in right now for some reason). I'll also be pointing attendees to our Discord, Matrix, Google Groups and GitHub.

Please post here if there are community projects you want to see highlighted. I can't guarantee I can cover everything in less than 20 minutes, but I'll do my best.

**Comment by adam-urbanczyk** [comment]
I'd definitely mention https://github.com/meadiode/cq_gears

**Comment by jchidley** [comment]
https://cqparts.github.io/ & https://cqparts.github.io/cqparts/doc/ 
https://github.com/bernhard-42/jupyter-cadquery - obviously

**Comment by jmwright** [comment]
@jchidley Thanks for the ideas.

The presentation was on Feb 5th, and I did cover jupyter-cadquery. Please also note that cqparts has not been updated for CadQuery 2.x. I created a fork a year or more ago that had the minimum set of updates to get it working, but never heard from the cq-parts core team on merging it and it's fallen out of date. That's why cqparts wasn't included in the presentation.

**Comment by jmwright** [comment]
The video for this event has been posted by the FOSDEM team so you can now watch/rewatch the presentation.

https://fosdem.org/2022/schedule/event/cadquery/

**Comment by dcowden** [comment]
thanks for sharing! cant wait to watch it!
