### ISSUE TITLE
Center when selecting different faces/planes

### ISSUE THREAD

**Issue by mryndzionek** [CadQuery/cadquery#961]
This code:
```py
import cadquery as cq

result = cq.Workplane("XY").box(1, 1, 1)
result = result.faces(">X").workplane().hole(0.5, 0.1)
result = result.faces(">Y").workplane().hole(0.5, 0.1)
```
gives this result:
![problem](https://user-images.githubusercontent.com/786191/149829000-66184dbc-5abc-4671-8da7-ff1e93bcf88f.png)

Why isn't the Y-plane hole also centered? I would expect `faces` to reset center, but it does not.
Also, if I change the order of selecting (Y and then X) planes it throws an exception (`Standard_ConstructionError`).

**Comment by Jojain** [comment]
Because the default for the workplane origin is ProjectedOrigin

You want to use `workplane(center option="CenterOfMass"`

**Comment by mryndzionek** [comment]
Hmmm, seems to be fairly standard thing, but is mentioned only once in documentation and only in context of assemblies.
Nevertheless thanks for help.
