### ISSUE TITLE
[EASY QUESTION] Exporting an assembly model as .stl format

### ISSUE THREAD

**Issue by traceforward** [CadQuery/cadquery#965]
I can not export an assembly model which I created with cq.Assembly() with exporters.exportSTL. How can I do that. Please help.
Thanks in advance.

**Comment by adam-urbanczyk** [comment]
Use `toCompound` and then export.

**Comment by Jojain** [comment]
@adam-urbanczyk Since this is not the first time someone ask this, shouldn't we consider the `exportStl` to automatically make a compound of the assembly ?
I'm pretty sure it's trivial to do, and would be more transparent for users

**Comment by adam-urbanczyk** [comment]
Maybe, but I really wonder what is the use of such an STL.

**Comment by jmwright** [comment]
This issue has already been addressed, but I'm going to post [this response](https://gitlab.com/kicad/libraries/kicad-packages3D-generator/-/issues/5#note_1226473401) here for archival purposes. It's a good explanation from someone in the KiCAD community of why you would want to fuse and print an assembly.
