### ISSUE TITLE
How to get the implemented wireframe in cadquery？

### ISSUE THREAD

**Issue by luoyu-123** [CadQuery/cadquery#987]
I want to get a 3D line frame of an entity in cadquery, but I don't see the corresponding column in the document. Is there such a function in cadquery?

**For example this is a picture of the entity**
![image](https://user-images.githubusercontent.com/59160360/153145513-a7860599-6dfd-4c75-94c7-063486252680.png)

**Here is the picture to get the wireframe**
![image](https://user-images.githubusercontent.com/59160360/153145697-9bd0921b-e21c-41ac-b6d6-d34008ff95fe.png)

################################
I saw this function on onshape. Does cadquery have a corresponding function?

**Comment by Jojain** [comment]
Do you want the wire display or the wires shapes objects ?

For the display : cadquery doesn't provide any visualisation directly.
For the wires objects you can use `wires()` to get all the wires objects of your workplane

**Comment by jmwright** [comment]
There are also buttons in the toolbar of CQ-editor to switch between solid and wireframe view (white and black square logos). However, that does not convert the CadQuery object to wireframe, it just shows the object that way temporarily.

**Comment by luoyu-123** [comment]
Thank you so much
