### ISSUE TITLE
Importing DXF from Kicad results in "outer wire is not closed"

### ISSUE THREAD

**Issue by crides** [CadQuery/cadquery#996]
Hi, I'm trying to convert to cadquery for one of my models. I need to import DXF from Kicad that matches the PCB design. However, the import results in "outer wire is not closed". The problematic file is `steno-User_Eco1.dxf` (had to upload a zip cuz github has extension filtering), while for `steno-Edge_Cuts.dxf` it's totally fine. The outline itself in Kicad is totally fine; all the start points and end points match up exactly, and importing to CAD software like Onshape produces a closed region that one can (for example) extrude

On Arch Linux, using CQ-editor `0.3.0dev`

[dxf.zip](https://github.com/CadQuery/cadquery/files/8063456/dxf.zip)

**Comment by crides** [comment]
Thanks. Setting it to `1e-4` works. So what would cause this inaccuracy? Would that be a Kicad exporting problem (but doesn't affect lines somehow)?

**Comment by adam-urbanczyk** [comment]
It seems that your DXF has wires with gaps bigger than `1e-6` and the importer does not consider those closed. I cannot say more than that, so indeed check on the Kicad side of things.

**Comment by fedorkotov** [comment]
By the way KiCAD can export 3D models of boards with all the components in STEP format which CadQuery can import. You can  use STEP produced by KiCAD as is or preprocess it in something visual like FreeCAD to remove the parts you don't need in CadQuery

**Comment by crides** [comment]
Yes. Though in this case the `User.Eco1` layer is from a outline of other components, and it's much easier to draw it by hand rather than generating it from the components (and doesn't need to change much).
